import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Plus, X, ListChecks, ChevronDown, CalendarClock, AlertTriangle } from "lucide-react";
import { useTasks, type Task } from "@/hooks/useTasks";
import { cn } from "@/lib/utils";

interface ProjectTasksTabProps {
  projectId: string;
}

function daysUntil(dateStr: string): number {
  const d = new Date(dateStr + "T12:00:00");
  const today = new Date(); today.setHours(0, 0, 0, 0);
  return Math.floor((d.getTime() - today.getTime()) / 86400000);
}

function categorize(task: Task): "overdue" | "today" | "week" | "later" {
  if (!task.dueDate) return "later";
  const d = daysUntil(task.dueDate);
  if (d < 0) return "overdue";
  if (d === 0) return "today";
  if (d <= 7) return "week";
  return "later";
}

const SECTION_META = {
  overdue: { label: "Vencidas", icon: AlertTriangle, color: "text-destructive" },
  today: { label: "Hoje", icon: CalendarClock, color: "text-amber-400" },
  week: { label: "Esta semana", icon: CalendarClock, color: "text-primary" },
  later: { label: "Futuras / Sem prazo", icon: ListChecks, color: "text-muted-foreground" },
} as const;

const SECTION_ORDER: Array<keyof typeof SECTION_META> = ["overdue", "today", "week", "later"];

function TaskRow({ task, onToggle, onDelete }: { task: Task; onToggle: () => void; onDelete: () => void }) {
  const dueBadge = task.dueDate ? (() => {
    const d = daysUntil(task.dueDate);
    if (d < 0) return { label: `${Math.abs(d)}d atraso`, color: "text-destructive" };
    if (d === 0) return { label: "Hoje", color: "text-amber-400" };
    if (d === 1) return { label: "Amanhã", color: "text-amber-400" };
    return { label: `em ${d}d`, color: "text-muted-foreground" };
  })() : null;

  return (
    <div className="flex items-start gap-2 rounded-lg px-2 py-1.5 hover:bg-secondary/30 transition-colors group">
      <Checkbox checked={task.completed} onCheckedChange={onToggle} className="shrink-0 mt-0.5" />
      <span className="flex-1 text-xs leading-snug">{task.description}</span>
      <div className="flex items-center gap-1 shrink-0">
        {dueBadge && (
          <span className={cn("text-[10px] font-mono-nums flex items-center gap-0.5", dueBadge.color)}>
            <CalendarClock className="h-3 w-3" />
            {dueBadge.label}
          </span>
        )}
        {task.autoGenerated && (
          <Badge variant="outline" className="text-[9px] h-4 px-1 border-border/40">{task.source}</Badge>
        )}
        <Button variant="ghost" size="icon" className="h-5 w-5 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-destructive" onClick={onDelete}>
          <X className="h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}

export default function ProjectTasksTab({ projectId }: ProjectTasksTabProps) {
  const { activeTasks, completedTasks, addTask, toggleTask, deleteTask } = useTasks();
  const [newTaskDesc, setNewTaskDesc] = useState("");
  const [completedOpen, setCompletedOpen] = useState(false);

  const projectActive = activeTasks.filter((t) => t.projectId === projectId);
  const projectCompleted = completedTasks.filter((t) => t.projectId === projectId);

  // Group by time
  const grouped: Record<string, Task[]> = { overdue: [], today: [], week: [], later: [] };
  projectActive.forEach((t) => { grouped[categorize(t)].push(t); });

  const handleAddTask = async () => {
    if (!newTaskDesc.trim()) return;
    await addTask({ description: newTaskDesc.trim(), projectId });
    setNewTaskDesc("");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <ListChecks className="h-4 w-4 text-primary" />
        <span className="text-sm font-semibold">Tarefas do Projeto</span>
        <Badge variant="secondary" className="text-[10px]">{projectActive.length}</Badge>
      </div>

      <div className="flex gap-2">
        <Input
          placeholder="Nova tarefa…"
          value={newTaskDesc}
          onChange={(e) => setNewTaskDesc(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter") handleAddTask(); }}
          className="h-8 text-sm"
        />
        <Button size="sm" className="h-8 px-2 shrink-0" onClick={handleAddTask} disabled={!newTaskDesc.trim()}>
          <Plus className="h-3.5 w-3.5" />
        </Button>
      </div>

      {projectActive.length === 0 && projectCompleted.length === 0 ? (
        <p className="text-sm text-muted-foreground text-center py-6">Nenhuma tarefa neste projeto ainda.</p>
      ) : (
        <div className="space-y-3">
          {SECTION_ORDER.map((key) => {
            const tasks = grouped[key];
            if (tasks.length === 0) return null;
            const meta = SECTION_META[key];
            const Icon = meta.icon;
            return (
              <div key={key}>
                <div className="flex items-center gap-1.5 mb-1.5 px-1">
                  <Icon className={cn("h-3.5 w-3.5", meta.color)} />
                  <span className={cn("text-xs font-semibold", meta.color)}>{meta.label}</span>
                  <Badge variant="outline" className="text-[9px] h-4 px-1">{tasks.length}</Badge>
                </div>
                <div className="space-y-0.5">
                  {tasks.map((task) => (
                    <TaskRow key={task.id} task={task} onToggle={() => toggleTask(task.id)} onDelete={() => deleteTask(task.id)} />
                  ))}
                </div>
              </div>
            );
          })}

          {/* Completed */}
          {projectCompleted.length > 0 && (
            <Collapsible open={completedOpen} onOpenChange={setCompletedOpen}>
              <CollapsibleTrigger asChild>
                <button className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors w-full px-1">
                  <ChevronDown className={cn("h-3 w-3 transition-transform", completedOpen && "rotate-180")} />
                  Concluídas ({projectCompleted.length})
                </button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <div className="space-y-0.5 mt-1 max-h-40 overflow-y-auto">
                  {projectCompleted.slice(0, 10).map((task) => (
                    <div key={task.id} className="flex items-center gap-2 rounded-lg px-2 py-1 opacity-60 hover:opacity-80">
                      <Checkbox checked onCheckedChange={() => toggleTask(task.id)} className="shrink-0" />
                      <span className="flex-1 text-xs line-through text-muted-foreground">{task.description}</span>
                    </div>
                  ))}
                </div>
              </CollapsibleContent>
            </Collapsible>
          )}
        </div>
      )}
    </div>
  );
}
