import { createContext, useContext, type ReactNode } from "react";

interface LanguageContextType {
  lang: "pt";
  setLang: (lang: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, string> = {
  // ── Nav ──────────────────────────────────────────────────────────────────────
  "nav.home": "Início",
  "nav.projects": "Projetos",
  "nav.finance": "Finanças",
  "nav.tutorial": "Tutorial",
  "nav.agenda": "Agenda",
  "nav.musicdna": "DNA Musical",
  "nav.musicdna.short": "DNA",
  "nav.professionals": "Contatos",
  "nav.captadores": "Captadores",
  "nav.settings": "Configurações",
  "nav.settings.short": "Config.",
  "nav.admin": "Admin",
  "nav.editais": "Editais",
  "nav.palcos": "Palcos",
  "nav.carreira": "Carreira",
  "nav.visualDirection": "Direção Visual",
  "nav.logout": "Sair",
  "nav.more": "Mais",
  "nav.user": "Usuário",
  "nav.artist": "Artista",
  "nav.section.tools": "Ferramentas",
  "nav.section.account": "Conta",

  // ── Dashboard ────────────────────────────────────────────────────────────────
  "dashboard.title": "Dashboard",
  "dashboard.hello": "Olá,",
  "dashboard.filterProject": "Filtrar projeto",
  "dashboard.allProjects": "Todos os projetos",
  "dashboard.newProject": "Novo Projeto",
  "dashboard.totalRevenue": "Receita Total",
  "dashboard.investment": "Investimento",
  "dashboard.result": "Resultado",
  "dashboard.margin": "Margem",
  "dashboard.myProjects": "Meus Projetos",
  "dashboard.noActiveProjects": "Nenhum projeto ativo.",
  "dashboard.checklist": "Checklist do Dia",
  "dashboard.newTask": "Nova tarefa…",
  "dashboard.allTasks": "Todas",
  "dashboard.loading": "Carregando…",
  "dashboard.noTasks": "Nenhuma tarefa pendente.",
  "dashboard.completed": "Concluídas",
  "dashboard.aiAssistant": "Assistente IA",
  "dashboard.lastTransactions": "Últimas Transações",
  "dashboard.viewAll": "Ver todas",
  "dashboard.upcomingReleases": "Próximos Lançamentos",
  "dashboard.viewProjects": "Ver projetos",
  "dashboard.noReleases": "Nenhum projeto chegou ao estágio de master ou lançamento ainda.",
  "dashboard.createProject": "Criar projeto",
  "dashboard.paid": "Pago",
  "dashboard.pending": "Pendente",
  "dashboard.readyToRelease": "Pronto p/ Lançar",
  "dashboard.inMaster": "Em Master",
  "dashboard.released": "Lançado",
  "dashboard.noDate": "Sem data",
  "dashboard.checklistUpdated": "Checklist atualizado!",
  "dashboard.checklistError": "Erro ao atualizar checklist",
  "dashboard.lastUpdate": "Última atualização:",
  "dashboard.updateChecklist": "Atualizar checklist",
  "dashboard.sendToAI": "Enviar para o assistente IA",

  // ── Dashboard: First-run onboarding ──────────────────────────────────────────
  "onboard.firstSteps": "Primeiros passos",
  "onboard.createFirstProject": "Vamos criar seu primeiro projeto",
  "onboard.desc": "Do rascunho ao lançamento — organize sua música, acompanhe o progresso e colabore com sua equipe em um só lugar.",
  "onboard.createBtn": "Criar seu primeiro projeto",
  "onboard.checklist": "Checklist de início",
  "onboard.allDone": "Tudo pronto! Agora é só criar música.",
  "onboard.step.create_project": "Criar seu primeiro projeto",
  "onboard.step.create_project.desc": "Registre nome, artista, BPM e etapa atual",
  "onboard.step.add_track": "Adicionar uma faixa ao projeto",
  "onboard.step.add_track.desc": "Organize as faixas com parâmetros de mix",
  "onboard.step.invite_partner": "Convidar um parceiro",
  "onboard.step.invite_partner.desc": "Adicione um músico, produtor ou engenheiro",
  "onboard.markPending": "Marcar como pendente",
  "onboard.markDone": "Marcar como feito",

  // ── Dashboard: Due date labels ───────────────────────────────────────────────
  "due.late": "atraso",
  "due.today": "Hoje",
  "due.tomorrow": "Amanhã",
  "due.in": "em",

  // ── Dashboard: Source labels ─────────────────────────────────────────────────
  "source.payment": "pagamento",
  "source.deadline": "prazo",
  "source.inactivity": "inatividade",
  "source.budget": "orçamento",
  "source.invite_pending": "convite",
  "source.master_check": "master",
  "source.release": "lançamento",
  "source.default": "tarefa",
  "source.manual": "manual",

  // ── Dashboard: AI chips ──────────────────────────────────────────────────────
  "ai.urgent": "urgente",
  "ai.urgents": "urgentes",
  "ai.createProject": "Criar projeto",
  "ai.recordingTips": "Dicas de gravação",
  "ai.lufsStreaming": "LUFS streaming",
  "ai.mixTip": "Dica de mix",
  "ai.checkMaster": "Checar master",
  "ai.techTip": "Dica técnica",

  // ── Projects page ────────────────────────────────────────────────────────────
  "projects.title": "Projetos",
  "projects.addProject": "Novo Projeto",
  "projects.newProject": "Novo Projeto",
  "projects.newProjectDesc": "Preencha as informações do seu projeto musical para acompanhar o progresso desde o rascunho até a distribuição.",
  "projects.projectName": "Nome do Projeto",
  "projects.projectNamePlaceholder": "Ex: Trap Beat Vol. 3",
  "projects.artistProducer": "Artista",
  "projects.artistPlaceholder": "Ex: DJ Flow",
  "projects.bpm": "BPM (batidas por minuto)",
  "projects.bpmHint": "Velocidade da música. Ex: 130 para house, 140 para trap",
  "projects.key": "Tonalidade (Key)",
  "projects.keyPlaceholder": "Ex: Am, C#, F",
  "projects.keyHint": "Tom musical do projeto",
  "projects.currentStage": "Etapa atual",
  "projects.stageHint": "Em qual fase o projeto está agora",
  "projects.create": "Criar",
  "projects.timeline": "Linha do Tempo",
  "projects.mixProgress": "Progresso do Mix",
  "projects.revenueEstimate": "Estimativa de Receita",
  "projects.empty": "Nenhum projeto ativo. Crie seu primeiro projeto!",
  "projects.editProject": "Editar Projeto",

  // Stages
  "stage.inicio": "Projeto Iniciado",
  "stage.gravacao": "Gravação",
  "stage.mix": "Mix",
  "stage.master": "Master",
  "stage.upload": "Upload (check de áudio)",
  "stage.lancado": "Lançado",
  "stage.rough": "Projeto Iniciado",
  "stage.inicio.desc": "Projeto iniciado",
  "stage.gravacao.desc": "Gravação em andamento",
  "stage.mix.desc": "Mixagem em andamento",
  "stage.master.desc": "Masterização",
  "stage.upload.desc": "Check de áudio e upload",
  "stage.lancado.desc": "Projeto lançado",

  // Table headers
  "table.project": "Projeto",
  "table.artist": "Artista",
  "table.upload": "Upload",

  // Team
  "team.title": "Equipe",
  "team.add": "Adicionar",
  "team.addProfessional": "Adicionar Profissional",
  "team.addProfessionalDesc": "Adicione um profissional à equipe de",
  "team.name": "Nome",
  "team.namePlaceholder": "Ex: João Silva",
  "team.role": "Função",
  "team.rolePlaceholder": "Ex: Guitarrista, Produtor",
  "team.instrument": "Instrumento",
  "team.instrumentPlaceholder": "Ex: Guitarra, Vocal",
  "team.fee": "Cachê (R$)",
  "team.email": "E-mail",
  "team.phone": "Telefone",
  "team.phonePlaceholder": "(11) 99999-0000",
  "team.notes": "Observações",
  "team.notesPlaceholder": "Anotações sobre o profissional...",
  "team.empty": "Nenhum profissional adicionado ainda.",

  // Finance
  "finance.title": "Transações",
  "finance.newTransaction": "Nova Transação",
  "finance.editTransaction": "Editar Transação",
  "finance.formDesc": "Registre uma receita ou despesa vinculada a um projeto.",
  "finance.income": "Receita",
  "finance.expense": "Despesa",
  "finance.description": "Descrição",
  "finance.descPlaceholder": "Ex: Venda beat exclusivo",
  "finance.amount": "Valor (R$)",
  "finance.date": "Data",
  "finance.project": "Projeto",
  "finance.selectProject": "Selecionar projeto",
  "finance.category": "Categoria",
  "finance.selectCategory": "Selecionar categoria",
  "finance.cancel": "Cancelar",
  "finance.save": "Salvar",
  "finance.created": "Transação criada!",
  "finance.updated": "Transação atualizada!",
  "finance.deleted": "Transação excluída!",
  "finance.projectTitle": "Financeiro do Projeto",
  "finance.totalIncome": "Receitas",
  "finance.totalExpense": "Despesas",
  "finance.profitLabel": "Lucro/Prejuízo",
  "finance.margin": "Margem",
  "finance.viewAll": "Ver transações",
  "finance.allProjects": "Todos os projetos",
  "finance.allTypes": "Todos os tipos",
  "finance.allMonths": "Todos os meses",
  "finance.actions": "Ações",
  "finance.noTransactions": "Nenhuma transação encontrada.",
  "finance.deleteTitle": "Excluir transação",
  "finance.deleteDesc": "Tem certeza que deseja excluir esta transação?",
  "finance.deleteConfirm": "Excluir",
  "finance.costOfProduction": "Custos de Produção",
  "finance.investment": "Investimento",
  "finance.result": "Resultado",
  "finance.contractIncome": "Receita de Contratos",
  "finance.titleArtist": "Finanças",
  "finance.paid": "Pago?",
  "finance.paidBadge": "Pago",
  "finance.pendingBadge": "Pendente",
  "finance.status": "Status",
  "finance.notes": "Observações",
  "finance.notesPlaceholder": "Ex: Pago via PIX",
  "finance.paidOn": "✓ Pago",
  "finance.paidOff": "⏳ Pendente",
  "finance.customCategory": "Especifique a categoria",
  "finance.customCategoryPlaceholder": "Ex: Cachê de participação especial",
  "finance.noProject": "Nenhum projeto",
  "finance.optional": "(opcional)",
  "finance.saveTransaction": "Salvar Transação",
  "finance.saving": "Salvando…",
  "finance.saveError": "Erro ao salvar transação. Tente novamente.",
  "finance.selectDate": "Selecionar data",
  "finance.descRequired": "Informe a descrição",
  "finance.amountRequired": "Valor deve ser maior que zero",
  "finance.categoryRequired": "Selecione uma categoria",
  "finance.customCategoryRequired": "Especifique a categoria personalizada",

  // Project commercial fields
  "projects.projectType": "Tipo do Projeto",
  "projects.single": "Single",
  "projects.ep": "EP",
  "projects.album": "Álbum",
  "projects.beat": "Beat / Base",
  "projects.trilha_guia": "Trilha Guia",
  "projects.feat": "Feat.",
  "projects.trackCount": "Número de Faixas",
  "projects.totalContract": "Valor Contratado (R$)",
  "projects.totalContractPlaceholder": "Valor total acordado",
  "projects.amountPaid": "Valor já Pago (R$)",
  "projects.amountPaidPlaceholder": "Quanto já foi recebido",
  "projects.estimatedMonths": "Tempo Previsto (meses)",
  "projects.balance": "Saldo a Receber",
  "projects.paymentProgress": "Progresso de Pagamento",
  "projects.commercialInfo": "Informações Comerciais",
  "projects.notDefined": "Não definido",
  "projects.tracks": "faixas",
  "projects.paidWarning": "Valor pago não pode ser maior que o valor contratado",

  // ── Settings ─────────────────────────────────────────────────────────────────
  "settings.title": "Configurações",
  "settings.myProfile": "Meu Perfil",
  "settings.inGlobalBank": "No banco global",
  "settings.displayName": "Nome de Exibição",
  "settings.displayNameDesc": "Como você aparece no Dashboard",
  "settings.name": "Nome",
  "settings.email": "E-mail",
  "settings.saving": "Salvando...",
  "settings.save": "Salvar",
  "settings.nameUpdated": "Nome atualizado com sucesso",
  "settings.appearance": "Aparência",
  "settings.lightTheme": "Tema claro ativo",
  "settings.light": "Claro",
  "settings.pushNotifications": "Notificações Push",
  "settings.pushDesc": "Receba alertas de novas mensagens e mudanças de status mesmo com o app fechado",
  "settings.pushNotSupported": "Seu navegador não suporta notificações push.",
  "settings.pushEnabled": "Push ativado",
  "settings.pushDisabled": "Push desativado",
  "settings.pushDenied": "Permissão bloqueada no navegador",
  "settings.pushEnabledDesc": "Você receberá notificações de chat e status",
  "settings.pushDisabledDesc": "Ative para ser notificado em tempo real",
  "settings.enable": "Ativar",
  "settings.disable": "Desativar",
  "settings.pushDisabledToast": "Notificações push desativadas",
  "settings.pushEnabledToast": "Notificações push ativadas!",
  "settings.pushDeniedToast": "Permissão negada pelo navegador. Habilite nas configurações do browser.",
  "settings.pushErrorToast": "Não foi possível ativar as notificações.",
  "settings.demoData": "Dados de Demonstração",
  "settings.demoDesc": "Crie projetos e contatos de exemplo para explorar todas as funcionalidades",
  "settings.demoProjects": "Projetos",
  "settings.demoContacts": "Contatos & Avaliações",
  "settings.demoRatings": "avaliações de exemplo incluídas",
  "settings.createSampleProjects": "Criar projetos de exemplo",
  "settings.creatingSampleProjects": "Criando projetos…",
  "settings.createSampleContacts": "Criar contatos de exemplo",
  "settings.creatingSampleContacts": "Criando contatos…",
  "settings.allProjectsExist": "Todos os projetos de exemplo já existem.",
  "settings.projectsCreated": "projeto(s) de exemplo criado(s)!",
  "settings.contactsExist": "Contatos e avaliações de exemplo já existem.",
  "settings.contactsCreated": "Contatos de exemplo criados com sucesso!",
  "settings.checklistRules": "Regras do Checklist do Dia",
  "settings.checklistDesc": "Ative ou desative alertas automáticos e ajuste os limites de cada regra",
  "settings.ruleEnabled": "ativado",
  "settings.ruleDisabled": "desativado",

  // ── Task rule labels ─────────────────────────────────────────────────────────
  "rule.inactivity": "Inatividade em Projetos",
  "rule.inactivity.desc": "Alerta quando um projeto fica sem atualização por muitos dias.",
  "rule.inactivity.param": "Dias sem atividade",
  "rule.budget": "Alerta de Gastos",
  "rule.budget.desc": "Avisa quando despesas do mês se aproximam de um limite definido.",
  "rule.budget.param": "Percentual do limite de gastos (%)",
  "rule.invite_pending": "Convites sem Resposta",
  "rule.invite_pending.desc": "Lembra de convites pendentes após alguns dias.",
  "rule.invite_pending.param": "Dias sem resposta",
  "rule.deadline": "Prazo de Profissional",
  "rule.deadline.desc": "Antecipa entregas com prazo próximo.",
  "rule.deadline.param": "Dias de antecedência",
  "rule.master_check": "Checklist Técnico (Master)",
  "rule.master_check.desc": "Avisa sobre projetos parados na etapa de masterização.",
  "rule.master_check.param": "Dias na etapa Master",
  "rule.release": "Próximos Lançamentos",
  "rule.release.desc": "Prepara para datas de lançamento que se aproximam.",
  "rule.release.param": "Dias de antecedência",

  // ── Notifications ────────────────────────────────────────────────────────────
  "notifications.title": "Notificações",
  "notifications.markAllRead": "Marcar todas como lidas",
  "notifications.empty": "Nenhuma notificação",
  "notifications.now": "agora",

  // ── Legal ────────────────────────────────────────────────────────────────────
  "legal.back": "Voltar",
  "legal.terms": "Termos de Uso",
  "legal.privacy": "Política de Privacidade",

  // ── Auth ──────────────────────────────────────────────────────────────────────
  "auth.login": "Entrar",
  "auth.signup": "Criar conta",
  "auth.forgot": "Esqueceu a senha?",
  "auth.email": "E-mail",
  "auth.password": "Senha",
  "auth.noAccount": "Não tem conta?",
  "auth.hasAccount": "Já tem conta?",

  // ── Misc ─────────────────────────────────────────────────────────────────────
  "misc.loading": "Carregando...",
  "misc.confirm": "Confirmar",
  "misc.delete": "Excluir",
  "misc.edit": "Editar",
  "misc.close": "Fechar",
  "misc.search": "Buscar",
  "misc.cancel": "Cancelar",

  // ── Agenda ──────────────────────────────────────────────────────────────────
  "agenda.title": "Agenda",
  "agenda.newEvent": "Novo Evento",
  "agenda.event": "evento",
  "agenda.events": "eventos",
  "agenda.noEvents": "Nenhum evento ainda. Clique em \"Novo\" para começar.",
  "agenda.noEventsFiltered": "Nenhum evento encontrado para os filtros selecionados.",
  "agenda.createFirst": "Criar primeiro evento",
  "agenda.deleteTitle": "Excluir evento",
  "agenda.deleteDesc": "Tem certeza? Esta ação não pode ser desfeita.",
  "agenda.eventCreated": "Evento criado!",
  "agenda.eventUpdated": "Evento atualizado!",
  "agenda.eventDeleted": "Evento excluído",
  "agenda.filterAll": "Todos",
  "agenda.filterToday": "Hoje",
  "agenda.filterWeek": "Próximos 7 dias",
  "agenda.filterMonth": "Este mês",
  "agenda.allTypes": "Todos os tipos",
  "agenda.allProjects": "Todos os projetos",
  "agenda.eventType": "Tipo de evento",
  "agenda.editEvent": "Editar Evento",
  "agenda.formDesc": "Preencha os dados para adicionar um evento à sua agenda.",
  "agenda.formEditDesc": "Atualize os dados do evento.",
  "agenda.titleLabel": "Título do Evento",
  "agenda.titleRequired": "Informe o título do evento",
  "agenda.endBeforeStart": "Término deve ser após o início",
  "agenda.conflictConfirmed": "Conflito confirmado — clique em Salvar para continuar",
  "agenda.cancel": "Cancelar",
  "agenda.saveEvent": "Salvar Evento",
  "agenda.saving": "Salvando...",
  "agenda.saveAnyway": "Salvar mesmo assim",
  "agenda.noProject": "Nenhum",

  // ── Welcome ─────────────────────────────────────────────────────────────────
  "welcome.beta": "Versão Beta — bugs podem ocorrer. Seu feedback é essencial.",
  "welcome.badge": "IA + Gestão para artistas independentes",
  "welcome.subtitle": "Do rascunho ao lançamento —",
  "welcome.subtitleBold": "projetos, finanças, parceiros e agenda",
  "welcome.subtitleAI": "IA integrada",
  "welcome.featuresLabel": "Tudo que você precisa em um só lugar",
  "welcome.previewLabel": "Veja como funciona na prática",
  "welcome.ctaTitle": "Pronto para assumir o controle da sua carreira?",
  "welcome.ctaSubtitle": "Gratuito. Sem cartão de crédito.",
  "welcome.ctaEmail": "Começar grátis com e-mail",
  "welcome.ctaGoogle": "Entrar com Google",
  "welcome.ctaLogin": "Já tenho conta — entrar com e-mail",
  "welcome.terms": "Termos de Uso",
  "welcome.privacy": "Privacidade",
  "welcome.with": "com",

  // ── Editais ─────────────────────────────────────────────────────────────────
  "editais.title": "Editais",
  "editais.subtitle": "Encontre chamadas públicas de fomento para música e audiovisual",
  "editais.searchPlaceholder": "Ex: editais de música em São Paulo, ProAC aberto, Funarte 2026...",
  "editais.search": "Buscar",
  "editais.searching": "Buscando…",
  "editais.searchHint": "A IA vasculha portais federais, estaduais e municipais para encontrar oportunidades de fomento.",
  "editais.tabSearch": "Buscar",
  "editais.tabSaved": "Meus Editais",
  "editais.emptyTitle": "Encontre editais culturais para seu projeto",
  "editais.emptyDesc": "Digite uma busca e a IA vasculha portais federais, estaduais e municipais para encontrar oportunidades de fomento para artistas.",
  "editais.metrics": "Métricas",
  "editais.noSaved": "Nenhum edital salvo ainda.",
  "editais.noSavedHint": "Busque editais na aba Buscar e salve os que interessam.",
  "editais.results": "Resultados",
  "editais.noResults": "Nenhum edital encontrado para esta busca.",
  
  "editais.linkProject": "Vincular ao projeto",
  "editais.noProject": "Sem vínculo",
  "editais.save": "Salvar no MusicOS.ai",
  "editais.saveSelected": "Salvar selecionados",
  "editais.saveAll": "Salvar todos",
  "editais.exportCSV": "Exportar CSV",
  "editais.saved": "Editais salvos",
  "editais.edit": "Editar edital",
  "editais.editSave": "Salvar alterações",
  "editais.inferred": "Dados inferidos pela IA",
  "editais.searchSaved": "Buscar por título ou órgão…",
  "editais.showing": "Exibindo",
  "editais.of": "de",
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const t = (key: string): string => {
    return translations[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang: "pt", setLang: () => {}, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
