import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "pt" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Lang, string>> = {
  // ── Nav ──────────────────────────────────────────────────────────────────────
  "nav.home": { pt: "Início", en: "Home" },
  "nav.projects": { pt: "Projetos", en: "Projects" },
  "nav.finance": { pt: "Finanças", en: "Finance" },
  "nav.tutorial": { pt: "Tutorial", en: "Tutorial" },
  "nav.agenda": { pt: "Agenda", en: "Schedule" },
  "nav.musicdna": { pt: "DNA Musical", en: "Music DNA" },
  "nav.professionals": { pt: "Contatos", en: "Contacts" },
  "nav.settings": { pt: "Configurações", en: "Settings" },
  "nav.admin": { pt: "Admin", en: "Admin" },
  "nav.logout": { pt: "Sair", en: "Log out" },
  "nav.user": { pt: "Usuário", en: "User" },
  "nav.artist": { pt: "Artista", en: "Artist" },

  // ── Dashboard ────────────────────────────────────────────────────────────────
  "dashboard.title": { pt: "Dashboard", en: "Dashboard" },
  "dashboard.hello": { pt: "Olá,", en: "Hello," },
  "dashboard.filterProject": { pt: "Filtrar projeto", en: "Filter project" },
  "dashboard.allProjects": { pt: "Todos os projetos", en: "All projects" },
  "dashboard.newProject": { pt: "Novo Projeto", en: "New Project" },
  "dashboard.totalRevenue": { pt: "Receita Total", en: "Total Revenue" },
  "dashboard.investment": { pt: "Investimento", en: "Investment" },
  "dashboard.result": { pt: "Resultado", en: "Result" },
  "dashboard.margin": { pt: "Margem", en: "Margin" },
  "dashboard.myProjects": { pt: "Meus Projetos", en: "My Projects" },
  "dashboard.noActiveProjects": { pt: "Nenhum projeto ativo.", en: "No active projects." },
  "dashboard.checklist": { pt: "Checklist do Dia", en: "Daily Checklist" },
  "dashboard.newTask": { pt: "Nova tarefa…", en: "New task…" },
  "dashboard.allTasks": { pt: "Todas", en: "All" },
  "dashboard.loading": { pt: "Carregando…", en: "Loading…" },
  "dashboard.noTasks": { pt: "Nenhuma tarefa pendente. 🎉", en: "No pending tasks. 🎉" },
  "dashboard.completed": { pt: "Concluídas", en: "Completed" },
  "dashboard.aiAssistant": { pt: "Assistente IA", en: "AI Assistant" },
  "dashboard.lastTransactions": { pt: "Últimas Transações", en: "Latest Transactions" },
  "dashboard.viewAll": { pt: "Ver todas", en: "View all" },
  "dashboard.upcomingReleases": { pt: "Próximos Lançamentos", en: "Upcoming Releases" },
  "dashboard.viewProjects": { pt: "Ver projetos", en: "View projects" },
  "dashboard.noReleases": { pt: "Nenhum projeto chegou ao estágio de master ou lançamento ainda.", en: "No projects have reached the master or release stage yet." },
  "dashboard.createProject": { pt: "Criar projeto", en: "Create project" },
  "dashboard.paid": { pt: "Pago", en: "Paid" },
  "dashboard.pending": { pt: "Pendente", en: "Pending" },
  "dashboard.readyToRelease": { pt: "Pronto p/ Lançar", en: "Ready to Release" },
  "dashboard.inMaster": { pt: "Em Master", en: "In Master" },
  "dashboard.released": { pt: "Lançado", en: "Released" },
  "dashboard.noDate": { pt: "Sem data", en: "No date" },
  "dashboard.checklistUpdated": { pt: "Checklist atualizado!", en: "Checklist updated!" },
  "dashboard.checklistError": { pt: "Erro ao atualizar checklist", en: "Error updating checklist" },
  "dashboard.lastUpdate": { pt: "Última atualização:", en: "Last update:" },
  "dashboard.updateChecklist": { pt: "Atualizar checklist", en: "Update checklist" },
  "dashboard.sendToAI": { pt: "Enviar para o assistente IA", en: "Send to AI assistant" },

  // ── Dashboard: First-run onboarding ──────────────────────────────────────────
  "onboard.firstSteps": { pt: "Primeiros passos", en: "First steps" },
  "onboard.createFirstProject": { pt: "Vamos criar seu primeiro projeto", en: "Let's create your first project" },
  "onboard.desc": {
    pt: "Do rascunho ao lançamento — organize sua música, acompanhe o progresso e colabore com sua equipe em um só lugar.",
    en: "From draft to release — organize your music, track progress and collaborate with your team in one place.",
  },
  "onboard.createBtn": { pt: "Criar seu primeiro projeto", en: "Create your first project" },
  "onboard.checklist": { pt: "Checklist de início", en: "Getting started" },
  "onboard.allDone": { pt: "🎉 Tudo pronto! Agora é só criar música.", en: "🎉 All set! Now just make music." },
  "onboard.step.create_project": { pt: "Criar seu primeiro projeto", en: "Create your first project" },
  "onboard.step.create_project.desc": { pt: "Registre nome, artista, BPM e etapa atual", en: "Enter name, artist, BPM and current stage" },
  "onboard.step.add_track": { pt: "Adicionar uma faixa ao projeto", en: "Add a track to the project" },
  "onboard.step.add_track.desc": { pt: "Organize as faixas com parâmetros de mix", en: "Organize tracks with mix parameters" },
  "onboard.step.invite_partner": { pt: "Convidar um parceiro", en: "Invite a partner" },
  "onboard.step.invite_partner.desc": { pt: "Adicione um músico, produtor ou engenheiro", en: "Add a musician, producer or engineer" },
  "onboard.markPending": { pt: "Marcar como pendente", en: "Mark as pending" },
  "onboard.markDone": { pt: "Marcar como feito", en: "Mark as done" },

  // ── Dashboard: Due date labels ───────────────────────────────────────────────
  "due.late": { pt: "atraso", en: "late" },
  "due.today": { pt: "Hoje", en: "Today" },
  "due.tomorrow": { pt: "Amanhã", en: "Tomorrow" },
  "due.in": { pt: "em", en: "in" },

  // ── Dashboard: Source labels ─────────────────────────────────────────────────
  "source.payment": { pt: "pagamento", en: "payment" },
  "source.deadline": { pt: "prazo", en: "deadline" },
  "source.inactivity": { pt: "inatividade", en: "inactivity" },
  "source.budget": { pt: "orçamento", en: "budget" },
  "source.invite_pending": { pt: "convite", en: "invite" },
  "source.master_check": { pt: "master", en: "master" },
  "source.release": { pt: "lançamento", en: "release" },
  "source.default": { pt: "tarefa", en: "task" },
  "source.manual": { pt: "manual", en: "manual" },

  // ── Dashboard: AI chips ──────────────────────────────────────────────────────
  "ai.urgent": { pt: "urgente", en: "urgent" },
  "ai.urgents": { pt: "urgentes", en: "urgent" },
  "ai.createProject": { pt: "🎵 Criar projeto", en: "🎵 Create project" },
  "ai.recordingTips": { pt: "🎙️ Dicas de gravação", en: "🎙️ Recording tips" },
  "ai.lufsStreaming": { pt: "🔊 LUFS streaming", en: "🔊 LUFS streaming" },
  "ai.mixTip": { pt: "🎛️ Dica de mix", en: "🎛️ Mix tip" },
  "ai.checkMaster": { pt: "🔊 Checar master", en: "🔊 Check master" },
  "ai.techTip": { pt: "🎙️ Dica técnica", en: "🎙️ Tech tip" },

  // ── Projects page ────────────────────────────────────────────────────────────
  "projects.title": { pt: "Projetos", en: "Projects" },
  "projects.addProject": { pt: "Novo Projeto", en: "Add Project" },
  "projects.newProject": { pt: "Novo Projeto", en: "New Project" },
  "projects.newProjectDesc": {
    pt: "Preencha as informações do seu projeto musical para acompanhar o progresso desde o rascunho até a distribuição.",
    en: "Fill in your music project details to track progress from draft to distribution.",
  },
  "projects.projectName": { pt: "Nome do Projeto", en: "Project Name" },
  "projects.projectNamePlaceholder": { pt: "Ex: Trap Beat Vol. 3", en: "e.g. Trap Beat Vol. 3" },
  "projects.artistProducer": { pt: "Artista", en: "Artist" },
  "projects.artistPlaceholder": { pt: "Ex: DJ Flow", en: "e.g. DJ Flow" },
  "projects.bpm": { pt: "BPM (batidas por minuto)", en: "BPM (beats per minute)" },
  "projects.bpmHint": { pt: "Velocidade da música. Ex: 130 para house, 140 para trap", en: "Tempo of the track. e.g. 130 for house, 140 for trap" },
  "projects.key": { pt: "Tonalidade (Key)", en: "Key" },
  "projects.keyPlaceholder": { pt: "Ex: Am, C#, F", en: "e.g. Am, C#, F" },
  "projects.keyHint": { pt: "Tom musical do projeto", en: "Musical key of the project" },
  "projects.currentStage": { pt: "Etapa atual", en: "Current Stage" },
  "projects.stageHint": { pt: "Em qual fase o projeto está agora", en: "Current phase of the project" },
  "projects.create": { pt: "Criar", en: "Create" },
  "projects.timeline": { pt: "Linha do Tempo", en: "Timeline" },
  "projects.mixProgress": { pt: "Progresso do Mix", en: "Mix Progress" },
  "projects.revenueEstimate": { pt: "Estimativa de Receita", en: "Revenue Estimate" },
  "projects.empty": { pt: "Nenhum projeto ativo. Crie seu primeiro projeto!", en: "No active projects. Create your first project!" },
  "projects.editProject": { pt: "Editar Projeto", en: "Edit Project" },

  // Stages
  "stage.inicio": { pt: "Projeto Iniciado", en: "Project Started" },
  "stage.gravacao": { pt: "Gravação", en: "Recording" },
  "stage.mix": { pt: "Mix", en: "Mix" },
  "stage.master": { pt: "Master", en: "Master" },
  "stage.upload": { pt: "Upload (check de áudio)", en: "Upload (audio check)" },
  "stage.lancado": { pt: "Lançado", en: "Released" },
  "stage.rough": { pt: "Projeto Iniciado", en: "Project Started" },
  "stage.inicio.desc": { pt: "Projeto iniciado", en: "Project started" },
  "stage.gravacao.desc": { pt: "Gravação em andamento", en: "Recording in progress" },
  "stage.mix.desc": { pt: "Mixagem em andamento", en: "Mixing in progress" },
  "stage.master.desc": { pt: "Masterização", en: "Mastering" },
  "stage.upload.desc": { pt: "Check de áudio e upload", en: "Audio check and upload" },
  "stage.lancado.desc": { pt: "Projeto lançado", en: "Project released" },

  // Table headers
  "table.project": { pt: "Projeto", en: "Project" },
  "table.artist": { pt: "Artista", en: "Artist" },
  "table.upload": { pt: "Upload", en: "Upload" },

  // Team
  "team.title": { pt: "Equipe", en: "Team" },
  "team.add": { pt: "Adicionar", en: "Add" },
  "team.addProfessional": { pt: "Adicionar Profissional", en: "Add Professional" },
  "team.addProfessionalDesc": { pt: "Adicione um profissional à equipe de", en: "Add a professional to the team of" },
  "team.name": { pt: "Nome", en: "Name" },
  "team.namePlaceholder": { pt: "Ex: João Silva", en: "e.g. John Smith" },
  "team.role": { pt: "Função", en: "Role" },
  "team.rolePlaceholder": { pt: "Ex: Guitarrista, Produtor", en: "e.g. Guitarist, Producer" },
  "team.instrument": { pt: "Instrumento", en: "Instrument" },
  "team.instrumentPlaceholder": { pt: "Ex: Guitarra, Vocal", en: "e.g. Guitar, Vocals" },
  "team.fee": { pt: "Cachê (R$)", en: "Fee (R$)" },
  "team.email": { pt: "E-mail", en: "Email" },
  "team.phone": { pt: "Telefone", en: "Phone" },
  "team.phonePlaceholder": { pt: "(11) 99999-0000", en: "(11) 99999-0000" },
  "team.notes": { pt: "Observações", en: "Notes" },
  "team.notesPlaceholder": { pt: "Anotações sobre o profissional...", en: "Notes about the professional..." },
  "team.empty": { pt: "Nenhum profissional adicionado ainda.", en: "No professionals added yet." },

  // Finance
  "finance.title": { pt: "Transações", en: "Transactions" },
  "finance.newTransaction": { pt: "Nova Transação", en: "New Transaction" },
  "finance.editTransaction": { pt: "Editar Transação", en: "Edit Transaction" },
  "finance.formDesc": { pt: "Registre uma receita ou despesa vinculada a um projeto.", en: "Record an income or expense linked to a project." },
  "finance.income": { pt: "Receita", en: "Income" },
  "finance.expense": { pt: "Despesa", en: "Expense" },
  "finance.description": { pt: "Descrição", en: "Description" },
  "finance.descPlaceholder": { pt: "Ex: Venda beat exclusivo", en: "e.g. Exclusive beat sale" },
  "finance.amount": { pt: "Valor (R$)", en: "Amount (R$)" },
  "finance.date": { pt: "Data", en: "Date" },
  "finance.project": { pt: "Projeto", en: "Project" },
  "finance.selectProject": { pt: "Selecionar projeto", en: "Select project" },
  "finance.category": { pt: "Categoria", en: "Category" },
  "finance.selectCategory": { pt: "Selecionar categoria", en: "Select category" },
  "finance.cancel": { pt: "Cancelar", en: "Cancel" },
  "finance.save": { pt: "Salvar", en: "Save" },
  "finance.created": { pt: "Transação criada!", en: "Transaction created!" },
  "finance.updated": { pt: "Transação atualizada!", en: "Transaction updated!" },
  "finance.deleted": { pt: "Transação excluída!", en: "Transaction deleted!" },
  "finance.projectTitle": { pt: "Financeiro do Projeto", en: "Project Finance" },
  "finance.totalIncome": { pt: "Receitas", en: "Income" },
  "finance.totalExpense": { pt: "Despesas", en: "Expenses" },
  "finance.profitLabel": { pt: "Lucro/Prejuízo", en: "Profit/Loss" },
  "finance.margin": { pt: "Margem", en: "Margin" },
  "finance.viewAll": { pt: "Ver transações", en: "View transactions" },
  "finance.allProjects": { pt: "Todos os projetos", en: "All projects" },
  "finance.allTypes": { pt: "Todos os tipos", en: "All types" },
  "finance.allMonths": { pt: "Todos os meses", en: "All months" },
  "finance.actions": { pt: "Ações", en: "Actions" },
  "finance.noTransactions": { pt: "Nenhuma transação encontrada.", en: "No transactions found." },
  "finance.deleteTitle": { pt: "Excluir transação", en: "Delete transaction" },
  "finance.deleteDesc": { pt: "Tem certeza que deseja excluir esta transação?", en: "Are you sure you want to delete this transaction?" },
  "finance.deleteConfirm": { pt: "Excluir", en: "Delete" },
  "finance.costOfProduction": { pt: "Custos de Produção", en: "Production Costs" },
  "finance.investment": { pt: "Investimento", en: "Investment" },
  "finance.result": { pt: "Resultado", en: "Result" },
  "finance.contractIncome": { pt: "Receita de Contratos", en: "Contract Income" },
  "finance.titleArtist": { pt: "Finanças", en: "Finances" },
  "finance.paid": { pt: "Pago?", en: "Paid?" },
  "finance.paidBadge": { pt: "Pago", en: "Paid" },
  "finance.pendingBadge": { pt: "Pendente", en: "Pending" },
  "finance.status": { pt: "Status", en: "Status" },
  "finance.notes": { pt: "Observações", en: "Notes" },
  "finance.notesPlaceholder": { pt: "Ex: Pago via PIX", en: "e.g. Paid via PIX" },

  // Project commercial fields
  "projects.projectType": { pt: "Tipo do Projeto", en: "Project Type" },
  "projects.single": { pt: "Single", en: "Single" },
  "projects.ep": { pt: "EP", en: "EP" },
  "projects.album": { pt: "Álbum", en: "Album" },
  "projects.beat": { pt: "Beat / Base", en: "Beat / Base" },
  "projects.trilha_guia": { pt: "Trilha Guia", en: "Guide Track" },
  "projects.feat": { pt: "Feat.", en: "Feat." },
  "projects.trackCount": { pt: "Número de Faixas", en: "Track Count" },
  "projects.totalContract": { pt: "Valor Contratado (R$)", en: "Contract Value (R$)" },
  "projects.totalContractPlaceholder": { pt: "Valor total acordado", en: "Total agreed value" },
  "projects.amountPaid": { pt: "Valor já Pago (R$)", en: "Amount Paid (R$)" },
  "projects.amountPaidPlaceholder": { pt: "Quanto já foi recebido", en: "Amount already received" },
  "projects.estimatedMonths": { pt: "Tempo Previsto (meses)", en: "Estimated Time (months)" },
  "projects.balance": { pt: "Saldo a Receber", en: "Balance Due" },
  "projects.paymentProgress": { pt: "Progresso de Pagamento", en: "Payment Progress" },
  "projects.commercialInfo": { pt: "Informações Comerciais", en: "Commercial Info" },
  "projects.notDefined": { pt: "Não definido", en: "Not defined" },
  "projects.tracks": { pt: "faixas", en: "tracks" },
  "projects.paidWarning": { pt: "Valor pago não pode ser maior que o valor contratado", en: "Amount paid cannot exceed contract value" },

  // ── Settings ─────────────────────────────────────────────────────────────────
  "settings.title": { pt: "Configurações", en: "Settings" },
  "settings.myProfile": { pt: "Meu Perfil", en: "My Profile" },
  "settings.inGlobalBank": { pt: "No banco global", en: "In global directory" },
  "settings.displayName": { pt: "Nome de Exibição", en: "Display Name" },
  "settings.displayNameDesc": { pt: "Como você aparece no Dashboard", en: "How you appear on the Dashboard" },
  "settings.name": { pt: "Nome", en: "Name" },
  "settings.email": { pt: "E-mail", en: "Email" },
  "settings.saving": { pt: "Salvando...", en: "Saving..." },
  "settings.save": { pt: "Salvar", en: "Save" },
  "settings.nameUpdated": { pt: "Nome atualizado com sucesso", en: "Name updated successfully" },
  "settings.appearance": { pt: "Aparência", en: "Appearance" },
  "settings.lightTheme": { pt: "Tema claro ativo", en: "Light theme active" },
  "settings.light": { pt: "Claro", en: "Light" },
  "settings.pushNotifications": { pt: "Notificações Push", en: "Push Notifications" },
  "settings.pushDesc": { pt: "Receba alertas de novas mensagens e mudanças de status mesmo com o app fechado", en: "Receive alerts for new messages and status changes even with the app closed" },
  "settings.pushNotSupported": { pt: "Seu navegador não suporta notificações push.", en: "Your browser does not support push notifications." },
  "settings.pushEnabled": { pt: "Push ativado", en: "Push enabled" },
  "settings.pushDisabled": { pt: "Push desativado", en: "Push disabled" },
  "settings.pushDenied": { pt: "Permissão bloqueada no navegador", en: "Permission blocked in browser" },
  "settings.pushEnabledDesc": { pt: "Você receberá notificações de chat e status", en: "You will receive chat and status notifications" },
  "settings.pushDisabledDesc": { pt: "Ative para ser notificado em tempo real", en: "Enable for real-time notifications" },
  "settings.enable": { pt: "Ativar", en: "Enable" },
  "settings.disable": { pt: "Desativar", en: "Disable" },
  "settings.pushDisabledToast": { pt: "Notificações push desativadas", en: "Push notifications disabled" },
  "settings.pushEnabledToast": { pt: "Notificações push ativadas! 🔔", en: "Push notifications enabled! 🔔" },
  "settings.pushDeniedToast": { pt: "Permissão negada pelo navegador. Habilite nas configurações do browser.", en: "Permission denied by browser. Enable in browser settings." },
  "settings.pushErrorToast": { pt: "Não foi possível ativar as notificações.", en: "Could not enable notifications." },
  "settings.demoData": { pt: "Dados de Demonstração", en: "Demo Data" },
  "settings.demoDesc": { pt: "Crie projetos e contatos de exemplo para explorar todas as funcionalidades", en: "Create sample projects and contacts to explore all features" },
  "settings.demoProjects": { pt: "Projetos", en: "Projects" },
  "settings.demoContacts": { pt: "Contatos & Avaliações", en: "Contacts & Ratings" },
  "settings.demoRatings": { pt: "avaliações de exemplo incluídas", en: "sample ratings included" },
  "settings.createSampleProjects": { pt: "Criar projetos de exemplo", en: "Create sample projects" },
  "settings.creatingSampleProjects": { pt: "Criando projetos…", en: "Creating projects…" },
  "settings.createSampleContacts": { pt: "Criar contatos de exemplo", en: "Create sample contacts" },
  "settings.creatingSampleContacts": { pt: "Criando contatos…", en: "Creating contacts…" },
  "settings.allProjectsExist": { pt: "Todos os projetos de exemplo já existem.", en: "All sample projects already exist." },
  "settings.projectsCreated": { pt: "projeto(s) de exemplo criado(s)! 🎉", en: "sample project(s) created! 🎉" },
  "settings.contactsExist": { pt: "Contatos e avaliações de exemplo já existem.", en: "Sample contacts and ratings already exist." },
  "settings.checklistRules": { pt: "Regras do Checklist do Dia", en: "Daily Checklist Rules" },
  "settings.checklistDesc": { pt: "Ative ou desative alertas automáticos e ajuste os limites de cada regra", en: "Enable or disable automatic alerts and adjust thresholds for each rule" },
  "settings.ruleEnabled": { pt: "ativado", en: "enabled" },
  "settings.ruleDisabled": { pt: "desativado", en: "disabled" },

  // ── Task rule labels ─────────────────────────────────────────────────────────
  "rule.inactivity": { pt: "Inatividade em Projetos", en: "Project Inactivity" },
  "rule.inactivity.desc": { pt: "Alerta quando um projeto fica sem atualização por muitos dias.", en: "Alert when a project has no updates for many days." },
  "rule.inactivity.param": { pt: "Dias sem atividade", en: "Days without activity" },
  "rule.budget": { pt: "Alerta de Gastos", en: "Spending Alert" },
  "rule.budget.desc": { pt: "Avisa quando despesas do mês se aproximam de um limite definido.", en: "Warns when monthly expenses approach a defined limit." },
  "rule.budget.param": { pt: "Percentual do limite de gastos (%)", en: "Spending limit percentage (%)" },
  "rule.invite_pending": { pt: "Convites sem Resposta", en: "Unanswered Invites" },
  "rule.invite_pending.desc": { pt: "Lembra de convites pendentes após alguns dias.", en: "Reminds about pending invitations after a few days." },
  "rule.invite_pending.param": { pt: "Dias sem resposta", en: "Days without response" },
  "rule.deadline": { pt: "Prazo de Profissional", en: "Professional Deadline" },
  "rule.deadline.desc": { pt: "Antecipa entregas com prazo próximo.", en: "Anticipates deliveries with upcoming deadlines." },
  "rule.deadline.param": { pt: "Dias de antecedência", en: "Days in advance" },
  "rule.master_check": { pt: "Checklist Técnico (Master)", en: "Technical Checklist (Master)" },
  "rule.master_check.desc": { pt: "Avisa sobre projetos parados na etapa de masterização.", en: "Warns about projects stuck in the mastering stage." },
  "rule.master_check.param": { pt: "Dias na etapa Master", en: "Days in Master stage" },
  "rule.release": { pt: "Próximos Lançamentos", en: "Upcoming Releases" },
  "rule.release.desc": { pt: "Prepara para datas de lançamento que se aproximam.", en: "Prepares for approaching release dates." },
  "rule.release.param": { pt: "Dias de antecedência", en: "Days in advance" },

  // ── Notifications ────────────────────────────────────────────────────────────
  "notifications.title": { pt: "Notificações", en: "Notifications" },
  "notifications.markAllRead": { pt: "Marcar todas como lidas", en: "Mark all as read" },
  "notifications.empty": { pt: "Nenhuma notificação", en: "No notifications" },
  "notifications.now": { pt: "agora", en: "now" },

  // ── Legal ────────────────────────────────────────────────────────────────────
  "legal.back": { pt: "Voltar", en: "Back" },
  "legal.terms": { pt: "Termos de Uso", en: "Terms of Use" },
  "legal.privacy": { pt: "Política de Privacidade", en: "Privacy Policy" },

  // ── Auth ──────────────────────────────────────────────────────────────────────
  "auth.login": { pt: "Entrar", en: "Log in" },
  "auth.signup": { pt: "Criar conta", en: "Sign up" },
  "auth.forgot": { pt: "Esqueceu a senha?", en: "Forgot password?" },
  "auth.email": { pt: "E-mail", en: "Email" },
  "auth.password": { pt: "Senha", en: "Password" },
  "auth.noAccount": { pt: "Não tem conta?", en: "Don't have an account?" },
  "auth.hasAccount": { pt: "Já tem conta?", en: "Already have an account?" },

  // ── Misc ─────────────────────────────────────────────────────────────────────
  "misc.loading": { pt: "Carregando...", en: "Loading..." },
  "misc.confirm": { pt: "Confirmar", en: "Confirm" },
  "misc.delete": { pt: "Excluir", en: "Delete" },
  "misc.edit": { pt: "Editar", en: "Edit" },
  "misc.close": { pt: "Fechar", en: "Close" },
  "misc.search": { pt: "Buscar", en: "Search" },
  "misc.cancel": { pt: "Cancelar", en: "Cancel" },

  // ── Agenda ──────────────────────────────────────────────────────────────────
  "agenda.title": { pt: "Agenda", en: "Schedule" },
  "agenda.newEvent": { pt: "Novo Evento", en: "New Event" },
  "agenda.event": { pt: "evento", en: "event" },
  "agenda.events": { pt: "eventos", en: "events" },
  "agenda.noEvents": { pt: "Nenhum evento ainda. Clique em \"Novo Evento\" para começar.", en: "No events yet. Click \"New Event\" to get started." },
  "agenda.noEventsFiltered": { pt: "Nenhum evento encontrado para os filtros selecionados.", en: "No events found for the selected filters." },
  "agenda.createFirst": { pt: "Criar primeiro evento", en: "Create first event" },
  "agenda.deleteTitle": { pt: "Excluir evento", en: "Delete event" },
  "agenda.deleteDesc": { pt: "Tem certeza? Esta ação não pode ser desfeita.", en: "Are you sure? This action cannot be undone." },
  "agenda.eventCreated": { pt: "Evento criado!", en: "Event created!" },
  "agenda.eventUpdated": { pt: "Evento atualizado!", en: "Event updated!" },
  "agenda.eventDeleted": { pt: "Evento excluído", en: "Event deleted" },
  "agenda.filterAll": { pt: "Todos", en: "All" },
  "agenda.filterToday": { pt: "Hoje", en: "Today" },
  "agenda.filterWeek": { pt: "Próximos 7 dias", en: "Next 7 days" },
  "agenda.filterMonth": { pt: "Este mês", en: "This month" },
  "agenda.allTypes": { pt: "Todos os tipos", en: "All types" },
  "agenda.allProjects": { pt: "Todos os projetos", en: "All projects" },
  "agenda.eventType": { pt: "Tipo de evento", en: "Event type" },

  // ── Welcome ─────────────────────────────────────────────────────────────────
  "welcome.beta": { pt: "Versão Beta — bugs podem ocorrer. Seu feedback é essencial.", en: "Beta Version — bugs may occur. Your feedback is essential." },
  "welcome.badge": { pt: "IA + Gestão para artistas independentes", en: "AI + Management for independent artists" },
  "welcome.subtitle": { pt: "Do rascunho ao lançamento —", en: "From draft to release —" },
  "welcome.subtitleBold": { pt: "projetos, finanças, parceiros e agenda", en: "projects, finance, partners and schedule" },
  "welcome.subtitleAI": { pt: "IA integrada", en: "integrated AI" },
  "welcome.featuresLabel": { pt: "Tudo que você precisa em um só lugar", en: "Everything you need in one place" },
  "welcome.previewLabel": { pt: "Veja como funciona na prática", en: "See how it works in practice" },
  "welcome.ctaTitle": { pt: "Pronto para assumir o controle da sua carreira?", en: "Ready to take control of your career?" },
  "welcome.ctaSubtitle": { pt: "Gratuito. Sem cartão de crédito.", en: "Free. No credit card required." },
  "welcome.ctaEmail": { pt: "Começar grátis com e-mail", en: "Start free with email" },
  "welcome.ctaGoogle": { pt: "Entrar com Google", en: "Sign in with Google" },
  "welcome.ctaLogin": { pt: "Já tenho conta — entrar com e-mail", en: "Already have an account — sign in with email" },
  "welcome.terms": { pt: "Termos de Uso", en: "Terms of Use" },
  "welcome.privacy": { pt: "Privacidade", en: "Privacy" },
  "welcome.with": { pt: "com", en: "with" },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("pt");

  const t = (key: string): string => {
    return translations[key]?.[lang] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
