import { describe, it, expect, vi, beforeAll, afterAll } from "vitest";
import { categorizeTask, groupTasks } from "../useTasks";
import type { Task } from "../useTasks";

// Fix "today" to 2026-01-15 for all date-relative tests
beforeAll(() => {
  vi.useFakeTimers();
  vi.setSystemTime(new Date("2026-01-15T12:00:00Z"));
});
afterAll(() => {
  vi.useRealTimers();
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: "t-1",
    userId: "u-1",
    projectId: "p-1",
    description: "Do something",
    dueDate: null,
    completed: false,
    autoGenerated: false,
    source: "manual",
    sourceKey: "",
    createdAt: "2026-01-01T00:00:00Z",
    assignedTo: "",
    blocked: false,
    blockedReason: "",
    severity: "medium",
    taskArea: "geral",
    sourceModule: "",
    ...overrides,
  };
}

// ── categorizeTask ────────────────────────────────────────────────────────────

describe("categorizeTask", () => {
  it("returns 'blocked' for a blocked task regardless of due date", () => {
    expect(categorizeTask(makeTask({ blocked: true, dueDate: "2026-01-14" }))).toBe("blocked");
  });

  it("returns 'blocked' for a blocked task with no due date", () => {
    expect(categorizeTask(makeTask({ blocked: true, dueDate: null }))).toBe("blocked");
  });

  it("returns 'later' when there is no due date and task is not blocked", () => {
    expect(categorizeTask(makeTask({ dueDate: null }))).toBe("later");
  });

  it("returns 'overdue' when due date is in the past", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-01-14" }))).toBe("overdue");
  });

  it("returns 'today' when due date is today", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-01-15" }))).toBe("today");
  });

  it("returns 'week' when due date is within 7 days (exclusive today)", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-01-20" }))).toBe("week");
  });

  it("returns 'week' when due date is exactly 7 days away", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-01-22" }))).toBe("week");
  });

  it("returns 'later' when due date is more than 7 days away", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-01-23" }))).toBe("later");
  });

  it("returns 'later' for a far-future due date", () => {
    expect(categorizeTask(makeTask({ dueDate: "2026-06-01" }))).toBe("later");
  });
});

// ── groupTasks ────────────────────────────────────────────────────────────────

describe("groupTasks", () => {
  it("returns all empty arrays when given an empty list", () => {
    const result = groupTasks([]);
    expect(result.overdue).toHaveLength(0);
    expect(result.today).toHaveLength(0);
    expect(result.week).toHaveLength(0);
    expect(result.blocked).toHaveLength(0);
    expect(result.later).toHaveLength(0);
  });

  it("places an overdue task in the 'overdue' bucket", () => {
    const task = makeTask({ id: "t1", dueDate: "2026-01-10" });
    const result = groupTasks([task]);
    expect(result.overdue).toContain(task);
    expect(result.today).toHaveLength(0);
  });

  it("places a today task in the 'today' bucket", () => {
    const task = makeTask({ id: "t1", dueDate: "2026-01-15" });
    expect(groupTasks([task]).today).toContain(task);
  });

  it("places a this-week task in the 'week' bucket", () => {
    const task = makeTask({ id: "t1", dueDate: "2026-01-20" });
    expect(groupTasks([task]).week).toContain(task);
  });

  it("places a blocked task in 'blocked' even with an overdue date", () => {
    const task = makeTask({ id: "t1", blocked: true, dueDate: "2026-01-10" });
    const result = groupTasks([task]);
    expect(result.blocked).toContain(task);
    expect(result.overdue).toHaveLength(0);
  });

  it("places a no-due-date task in 'later'", () => {
    const task = makeTask({ id: "t1", dueDate: null });
    expect(groupTasks([task]).later).toContain(task);
  });

  it("distributes mixed tasks into their correct buckets", () => {
    const tasks = [
      makeTask({ id: "overdue", dueDate: "2026-01-01" }),
      makeTask({ id: "today",   dueDate: "2026-01-15" }),
      makeTask({ id: "week",    dueDate: "2026-01-20" }),
      makeTask({ id: "blocked", blocked: true }),
      makeTask({ id: "later",   dueDate: "2026-03-01" }),
    ];
    const result = groupTasks(tasks);
    expect(result.overdue.map((t) => t.id)).toContain("overdue");
    expect(result.today.map((t)   => t.id)).toContain("today");
    expect(result.week.map((t)    => t.id)).toContain("week");
    expect(result.blocked.map((t) => t.id)).toContain("blocked");
    expect(result.later.map((t)   => t.id)).toContain("later");
  });

  it("accumulates multiple tasks in the same bucket", () => {
    const tasks = [
      makeTask({ id: "t1", dueDate: "2026-01-14" }),
      makeTask({ id: "t2", dueDate: "2026-01-13" }),
    ];
    expect(groupTasks(tasks).overdue).toHaveLength(2);
  });

  it("every task appears in exactly one bucket", () => {
    const tasks = Array.from({ length: 5 }, (_, i) =>
      makeTask({ id: `t${i}`, dueDate: i % 2 === 0 ? "2026-01-20" : null })
    );
    const result = groupTasks(tasks);
    const total = Object.values(result).reduce((sum, arr) => sum + arr.length, 0);
    expect(total).toBe(tasks.length);
  });
});
