import { useCallback, useEffect } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { useAuth } from "@/contexts/AuthContext";


type TaskRow = Database["public"]["Tables"]["tasks"]["Row"];
type TaskUpdate = Database["public"]["Tables"]["tasks"]["Update"];

export type TaskSeverity = "low" | "medium" | "high" | "critical";
export type TaskArea = "mix" | "gravacao" | "financeiro" | "equipe" | "lancamento" | "geral";

export interface Task {
  id: string;
  userId: string;
  projectId: string | null;
  description: string;
  dueDate: string | null;
  completed: boolean;
  autoGenerated: boolean;
  source: string;
  sourceKey: string;
  createdAt: string;
  assignedTo: string;
  blocked: boolean;
  blockedReason: string;
  severity: TaskSeverity;
  taskArea: TaskArea;
  sourceModule: string;
}

function dbRowToTask(r: TaskRow): Task {
  return {
    id: r.id,
    userId: r.user_id,
    projectId: r.project_id,
    description: r.description,
    dueDate: r.due_date,
    completed: r.completed,
    autoGenerated: r.auto_generated,
    source: r.source,
    sourceKey: r.source_key ?? "",
    createdAt: r.created_at,
    assignedTo: r.assigned_to ?? "",
    blocked: r.blocked ?? false,
    blockedReason: r.blocked_reason ?? "",
    severity: (r.severity ?? "medium") as TaskSeverity,
    taskArea: (r.task_area ?? "geral") as TaskArea,
    sourceModule: r.source_module ?? "",
  };
}

// ── Time-based grouping helpers ──
export function daysUntil(dateStr: string): number {
  const d = new Date(dateStr + "T12:00:00");
  const today = new Date(); today.setHours(0, 0, 0, 0);
  return Math.floor((d.getTime() - today.getTime()) / 86400000);
}

export type TaskSection = "overdue" | "today" | "week" | "blocked" | "later";

export function categorizeTask(task: Task): TaskSection {
  if (task.blocked) return "blocked";
  if (!task.dueDate) return "later";
  const d = daysUntil(task.dueDate);
  if (d < 0) return "overdue";
  if (d === 0) return "today";
  if (d <= 7) return "week";
  return "later";
}

export function groupTasks(tasks: Task[]): Record<TaskSection, Task[]> {
  const groups: Record<TaskSection, Task[]> = { overdue: [], today: [], week: [], blocked: [], later: [] };
  tasks.forEach((t) => { groups[categorizeTask(t)].push(t); });
  return groups;
}

export const tasksKey = (userId?: string) => ["tasks", userId ?? "anon"] as const;

export function useTasks() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const key = tasksKey(user?.id);

  const { data: tasks = [], isLoading, refetch } = useQuery({
    queryKey: key,
    enabled: !!user,
    queryFn: async (): Promise<Task[]> => {
      const { data, error } = await supabase
        .from("tasks")
        .select("*")
        .eq("user_id", user!.id)
        .eq("dismissed", false)
        .order("due_date", { ascending: true, nullsFirst: false })
        .limit(200);
      if (error) throw error;
      return (data ?? []).map(dbRowToTask);
    },
  });

  const loading = isLoading;

  const setTasks = useCallback((updater: (prev: Task[]) => Task[]) => {
    queryClient.setQueryData<Task[]>(key, (prev) => updater(prev ?? []));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queryClient, user?.id]);

  // Realtime: tasks created by automations or other sessions land in the cache.
  useEffect(() => {
    if (!user) return;
    const channel = supabase
      .channel(`tasks:${user.id}`)
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "tasks", filter: `user_id=eq.${user.id}` },
        () => { queryClient.invalidateQueries({ queryKey: key }); },
      )
      .subscribe();
    return () => { supabase.removeChannel(channel); };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user?.id, queryClient]);

  const fetchTasks = useCallback(async () => { await refetch(); }, [refetch]);


  const addTask = useCallback(async (data: {
    description: string;
    dueDate?: string | null;
    projectId?: string | null;
    autoGenerated?: boolean;
    source?: string;
    assignedTo?: string;
    severity?: TaskSeverity;
    taskArea?: TaskArea;
    sourceModule?: string;
  }) => {
    if (!user) return null;
    const { data: row } = await supabase.from("tasks").insert({
      user_id: user.id,
      description: data.description,
      due_date: data.dueDate ?? null,
      project_id: data.projectId ?? null,
      auto_generated: data.autoGenerated ?? false,
      source: data.source ?? "manual",
      assigned_to: data.assignedTo ?? "",
      severity: data.severity ?? "medium",
      task_area: data.taskArea ?? "geral",
      source_module: data.sourceModule ?? "",
    }).select().single();
    if (row) {
      const task = dbRowToTask(row);
      setTasks((prev) => [...prev, task].sort((a, b) => {
        if (!a.dueDate && !b.dueDate) return 0;
        if (!a.dueDate) return 1;
        if (!b.dueDate) return -1;
        return a.dueDate.localeCompare(b.dueDate);
      }));
      return task;
    }
    return null;
  }, [user]);

  const toggleTask = useCallback(async (id: string) => {
    const task = tasks.find((t) => t.id === id);
    if (!task) return;
    setTasks((prev) => prev.map((t) => t.id === id ? { ...t, completed: !t.completed } : t));
    const { error } = await supabase.from("tasks").update({ completed: !task.completed }).eq("id", id);
    if (error) {
      // Rollback on failure
      setTasks((prev) => prev.map((t) => t.id === id ? { ...t, completed: task.completed } : t));
    }
  }, [tasks]);

  const deleteTask = useCallback(async (id: string) => {
    const task = tasks.find((t) => t.id === id);
    let error;
    if (task?.autoGenerated) {
      ({ error } = await supabase.from("tasks").update({ dismissed: true, completed: true }).eq("id", id));
    } else {
      ({ error } = await supabase.from("tasks").delete().eq("id", id));
    }
    if (!error) {
      setTasks((prev) => prev.filter((t) => t.id !== id));
    }
  }, [tasks]);

  const updateTask = useCallback(async (id: string, patch: Partial<Pick<Task, "assignedTo" | "blocked" | "blockedReason" | "severity" | "taskArea" | "description" | "dueDate" | "projectId">>) => {
    const dbPatch: TaskUpdate = {};
    if (patch.assignedTo !== undefined) dbPatch.assigned_to = patch.assignedTo;
    if (patch.blocked !== undefined) dbPatch.blocked = patch.blocked;
    if (patch.blockedReason !== undefined) dbPatch.blocked_reason = patch.blockedReason;
    if (patch.severity !== undefined) dbPatch.severity = patch.severity;
    if (patch.taskArea !== undefined) dbPatch.task_area = patch.taskArea;
    if (patch.description !== undefined) dbPatch.description = patch.description;
    if (patch.dueDate !== undefined) dbPatch.due_date = patch.dueDate;
    if (patch.projectId !== undefined) dbPatch.project_id = patch.projectId || null;

    await supabase.from("tasks").update(dbPatch).eq("id", id);
    setTasks((prev) => prev.map((t) => t.id === id ? { ...t, ...patch } : t));
  }, []);

  const ensureAutoTask = useCallback(async (key: string, data: {
    description: string;
    dueDate?: string;
    projectId?: string;
    source: string;
    severity?: TaskSeverity;
    taskArea?: TaskArea;
    sourceModule?: string;
  }) => {
    if (!user || !key) return;
    const payload = {
      user_id: user.id,
      description: data.description,
      due_date: data.dueDate ?? null,
      project_id: data.projectId ?? null,
      auto_generated: true,
      source: data.source,
      source_key: key,
      severity: data.severity ?? "medium",
      task_area: data.taskArea ?? "geral",
      source_module: data.sourceModule ?? "",
    };
    const { data: row } = await supabase
      .from("tasks")
      .upsert(payload, { onConflict: "user_id,source_key", ignoreDuplicates: true })
      .select()
      .single();
    if (row) {
      setTasks((prev) => {
        if (prev.some((t) => t.id === row.id)) return prev;
        return [dbRowToTask(row), ...prev];
      });
    }
  }, [user]);

  const activeTasks = tasks.filter((t) => !t.completed);
  const completedTasks = tasks.filter((t) => t.completed);

  return {
    tasks, activeTasks, completedTasks, loading,
    addTask, toggleTask, deleteTask, updateTask, ensureAutoTask,
    refresh: fetchTasks, groupTasks: () => groupTasks(activeTasks),
  };
}
