import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import {
  Plus, Headphones, DollarSign, CalendarClock, Clock, ChevronDown,
  Trash2, X, Mail, Activity, BarChart2, Disc3, Megaphone, RefreshCw, Bot,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useLanguage } from "@/contexts/LanguageContext";
import type { AITaskAssistantHandle } from "@/components/AITaskAssistant";

type SourceMeta = { icon: React.ElementType; color: string; label: string };

function getSourceMeta(source: string): SourceMeta {
  switch (source) {
    case "payment":      return { icon: DollarSign,   color: "text-amber-400",     label: "pagamento" };
    case "deadline":     return { icon: CalendarClock, color: "text-rose-400",      label: "prazo" };
    case "inactivity":   return { icon: Clock,         color: "text-muted-foreground", label: "inatividade" };
    case "budget":       return { icon: BarChart2,     color: "text-orange-400",    label: "orçamento" };
    case "invite_pending": return { icon: Mail,        color: "text-sky-400",       label: "convite" };
    case "master_check": return { icon: Disc3,         color: "text-violet-400",    label: "master" };
    case "release":      return { icon: Megaphone,     color: "text-green-400",     label: "lançamento" };
    default:             return { icon: Activity,      color: "text-primary",       label: source || "tarefa" };
  }
}

function formatDueDate(d: string | null) {
  if (!d) return null;
  const date = new Date(d + "T12:00:00");
  const today = new Date(); today.setHours(0,0,0,0);
  const diff = Math.floor((date.getTime() - today.getTime()) / 86400000);
  if (diff < 0) return { label: `${Math.abs(diff)}d atraso`, color: "text-destructive" };
  if (diff === 0) return { label: "Hoje", color: "text-amber-400" };
  if (diff === 1) return { label: "Amanhã", color: "text-amber-400" };
  if (diff <= 3) return { label: `em ${diff}d`, color: "text-amber-400/80" };
  return { label: `em ${diff}d`, color: "text-muted-foreground" };
}

interface Task {
  id: string;
  description: string;
  completed: boolean;
  source: string;
  autoGenerated: boolean;
  dueDate: string | null;
}

interface DailyChecklistProps {
  activeTasks: Task[];
  completedTasks: Task[];
  loading: boolean;
  onAddTask: (desc: string) => Promise<void>;
  onToggleTask: (id: string) => void;
  onDeleteTask: (id: string) => void;
  onRefresh: () => Promise<void>;
  refreshing: boolean;
  lastRefreshed: Date | null;
  hidden?: boolean;
  aiRef?: React.RefObject<AITaskAssistantHandle | null>;
}

export default function DailyChecklist({
  activeTasks, completedTasks, loading, onAddTask, onToggleTask, onDeleteTask,
  onRefresh, refreshing, lastRefreshed, hidden, aiRef,
}: DailyChecklistProps) {
  const { t } = useLanguage();
  const [newTaskDesc, setNewTaskDesc] = useState("");
  const [completedOpen, setCompletedOpen] = useState(false);
  const [taskFilter, setTaskFilter] = useState<string>("all");

  const handleAddTask = async () => {
    if (!newTaskDesc.trim()) return;
    await onAddTask(newTaskDesc.trim());
    setNewTaskDesc("");
  };

  return (
    <Card className={cn("glass-card animate-fade-in", hidden && "hidden")} style={{ animationDelay: "100ms" }}>
      <CardHeader className="pb-3">
        <CardTitle className="text-base flex items-center gap-2">
          <Headphones className="h-4 w-4 text-primary" /> Checklist do Dia
          {activeTasks.length > 0 && (
            <Badge variant="secondary" className="text-xs">{activeTasks.length}</Badge>
          )}
          <div className="ml-auto flex items-center gap-1.5">
            {lastRefreshed && !refreshing && (
              <span className="text-[10px] text-muted-foreground font-mono-nums">
                {lastRefreshed.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}
              </span>
            )}
            <Button
              variant="ghost"
              size="icon"
              className="h-6 w-6 text-muted-foreground hover:text-foreground"
              onClick={onRefresh}
              disabled={refreshing}
              title={lastRefreshed ? `Última atualização: ${lastRefreshed.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}` : "Atualizar checklist"}
            >
              <RefreshCw className={cn("h-3.5 w-3.5", refreshing && "animate-spin")} />
            </Button>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        {/* Add task input */}
        <div className="flex gap-2">
          <Input
            placeholder="Nova tarefa…"
            value={newTaskDesc}
            onChange={(e) => setNewTaskDesc(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter") handleAddTask(); }}
            className="h-8 text-sm"
          />
          <Button size="sm" className="h-8 px-2 shrink-0" onClick={handleAddTask} disabled={!newTaskDesc.trim()}>
            <Plus className="h-3.5 w-3.5" />
          </Button>
        </div>

        {/* Filter chips */}
        {activeTasks.length > 0 && (() => {
          const presentSources = Array.from(new Set(activeTasks.map((t) => t.source)));
          const chips = [
            { key: "all", label: "Todas" },
            ...["payment", "deadline", "master_check", "budget", "invite_pending", "inactivity", "release"]
              .filter((s) => presentSources.includes(s))
              .map((s) => ({ key: s, label: getSourceMeta(s).label })),
            ...(presentSources.includes("manual") ? [{ key: "manual", label: "manual" }] : []),
          ];
          if (chips.length <= 2) return null;
          return (
            <div className="flex flex-wrap gap-1.5">
              {chips.map(({ key, label }) => {
                const active = taskFilter === key;
                const meta = key !== "all" ? getSourceMeta(key) : null;
                return (
                  <button
                    key={key}
                    onClick={() => setTaskFilter(active ? "all" : key)}
                    className={cn(
                      "inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium border transition-all",
                      active
                        ? "bg-primary/20 border-primary/50 text-primary"
                        : "bg-secondary/50 border-border/40 text-muted-foreground hover:border-border hover:text-foreground"
                    )}
                  >
                    {meta && <meta.icon className={cn("h-2.5 w-2.5", active ? "text-primary" : meta.color)} />}
                    {label}
                    {key !== "all" && (
                      <span className="opacity-60">
                        {activeTasks.filter((t) => t.source === key).length}
                      </span>
                    )}
                  </button>
                );
              })}
            </div>
          );
        })()}

        {/* Active tasks */}
        {loading ? (
          <p className="text-xs text-muted-foreground text-center py-3 animate-pulse">{t("misc.loading")}</p>
        ) : activeTasks.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-3">Nenhuma tarefa pendente. 🎉</p>
        ) : (
          <div className="space-y-1 max-h-64 overflow-y-auto pr-1">
            {activeTasks
              .filter((t) => taskFilter === "all" || t.source === taskFilter)
              .map((task) => {
              const dueBadge = formatDueDate(task.dueDate);
              const meta = getSourceMeta(task.source);
              const SourceIcon = meta.icon;
              return (
                <div key={task.id} className="flex items-start gap-2 rounded-lg px-2 py-1.5 hover:bg-secondary/30 transition-colors group">
                  <Checkbox
                    checked={task.completed}
                    onCheckedChange={() => onToggleTask(task.id)}
                    className="shrink-0 mt-0.5"
                  />
                  {task.autoGenerated && (
                    <SourceIcon className={cn("h-3.5 w-3.5 shrink-0 mt-0.5", meta.color)} />
                  )}
                  <span className="flex-1 text-xs leading-snug">
                    {task.description}
                  </span>
                  <div className="flex items-center gap-1 shrink-0">
                    {dueBadge && (
                      <span className={cn("text-[10px] font-mono-nums flex items-center gap-0.5", dueBadge.color)}>
                        <CalendarClock className="h-3 w-3" />
                        {dueBadge.label}
                      </span>
                    )}
                    {task.autoGenerated && (
                      <Badge
                        variant="outline"
                        className={cn("text-[9px] h-4 px-1 border-border/40", meta.color)}
                      >
                        {meta.label}
                      </Badge>
                    )}
                    {(task.source === "music-dna" || task.description.startsWith("[DNA]")) && aiRef?.current && (
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-5 w-5 text-primary hover:text-primary/80"
                        title="Enviar para o assistente IA"
                        onClick={() => {
                          const desc = task.description.replace(/^\[DNA\]\s*/, "");
                          aiRef.current?.sendMessage(
                            `[Instrução: responda APENAS com os passos técnicos para aplicar esta técnica. Não mencione outras tarefas, prazos, vencimentos ou finanças.]\n\n${desc}`
                          );
                        }}
                      >
                        <Bot className="h-3 w-3" />
                      </Button>
                    )}
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-5 w-5 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-destructive"
                      onClick={() => onDeleteTask(task.id)}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Completed tasks collapsible */}
        {completedTasks.length > 0 && (
          <Collapsible open={completedOpen} onOpenChange={setCompletedOpen}>
            <CollapsibleTrigger asChild>
              <button className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mt-1 w-full">
                <ChevronDown className={cn("h-3 w-3 transition-transform", completedOpen && "rotate-180")} />
                Concluídas ({completedTasks.length})
              </button>
            </CollapsibleTrigger>
            <CollapsibleContent>
              <div className="space-y-1 mt-1 max-h-32 overflow-y-auto">
                {completedTasks.slice(0, 10).map((task) => (
                  <div key={task.id} className="flex items-center gap-2 rounded-lg px-2 py-1 group opacity-60 hover:opacity-80">
                    <Checkbox checked={true} onCheckedChange={() => onToggleTask(task.id)} className="shrink-0" />
                    <span className="flex-1 text-xs line-through text-muted-foreground">{task.description}</span>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-5 w-5 opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-destructive"
                      onClick={() => onDeleteTask(task.id)}
                    >
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </div>
                ))}
              </div>
            </CollapsibleContent>
          </Collapsible>
        )}
      </CardContent>
    </Card>
  );
}
