#!/usr/bin/env python3
"""
transform_csv_for_import.py

Transforma o CSV do jsp-audio-analyzer (colunas em PT-BR) para o formato
esperado pela edge function import-reference-tracks (colunas em inglês,
campos band / filename / genre obrigatórios).

Uso:
    python scripts/transform_csv_for_import.py \
        /Users/fernandoshaidmann/jsp-audio-analyzer/diagnostico_sonara_artistas.csv \
        --output /tmp/reference_tracks_import.csv

Após gerar o arquivo, faça upload em: /admin/reference-tracks
"""
from __future__ import annotations

import argparse
import ast
import csv
import os
import sys
from pathlib import Path

csv.field_size_limit(10_000_000)

# ---------------------------------------------------------------------------
# Mapeamento artista → gênero
# Cobre os ~100 artistas mais frequentes no CSV.
# Artistas não listados recebem o gênero DEFAULT_GENRE.
# Mapeamento artista → gênero (gerado por normalize_artist_genres.py — 900 artistas)
# Artistas não listados recebem o gênero DEFAULT_GENRE.
# ---------------------------------------------------------------------------
DEFAULT_GENRE = "Rock"

ARTIST_GENRE: dict[str, str] = {
    # ── Sertanejo ─────────────────────────────────────────
    'André e Andrade': 'Sertanejo',
    'Chitãozinho & Xororó': 'Sertanejo',
    'Chitãozinho e Xororó': 'Sertanejo',
    'Chitãozinho e Xororó/Chitãozinho & Xororó': 'Sertanejo',
    'Claudio Santana Sertanejo Na Veia': 'Sertanejo',
    'Cláudio Santana > Sertanejo na Veia': 'Sertanejo',
    'João Mineiro e Marciano': 'Sertanejo',
    'Mensageiro e Mexicano': 'Sertanejo',
    'Zilo & Zalo': 'Sertanejo',
    'Zé Béttio': 'Sertanejo',
    '\ufeffDanilo e Davi': 'Sertanejo',
    '\ufeffHenrique & Juliano': 'Sertanejo',
    '\ufeffJads & Jadson': 'Sertanejo',
    '\ufeffJads e Jadson': 'Sertanejo',
    '\ufeffMatogrosso & Mathias': 'Sertanejo',
    '\ufeffSimone Mendes': 'Sertanejo',
    '\ufeffZé Neto & Cristiano': 'Sertanejo',
    # ── Bossa Nova ────────────────────────────────────────
    'Antonio Carlos Jobim': 'Bossa Nova',
    'Baden Powell & Vinicius De Moraes': 'Bossa Nova',
    'Edu Lobo': 'Bossa Nova',
    'Elis Regina': 'Bossa Nova',
    'Elizete Cardoso': 'Bossa Nova',
    'Geraldo Vandre': 'Bossa Nova',
    'Jorge Ben': 'Bossa Nova',
    'Maria Bethania': 'Bossa Nova',
    'Marilia Medalha': 'Bossa Nova',
    'Miltinho': 'Bossa Nova',
    'Milton Nascimento': 'Bossa Nova',
    'Pery Ribeiro': 'Bossa Nova',
    'Tamba 4': 'Bossa Nova',
    'Tamba Trio': 'Bossa Nova',
    'Zelia Barbosa': 'Bossa Nova',
    # ── Chanson Francesa ──────────────────────────────────
    'Brice Pauset': 'Chanson Francesa',
    'Brigitte Fontaine': 'Chanson Francesa',
    'Celine Dion': 'Chanson Francesa',
    'Charles Trénet': 'Chanson Francesa',
    'David & Jonathon': 'Chanson Francesa',
    'Edgard Varese': 'Chanson Francesa',
    'Edgard Varèse': 'Chanson Francesa',
    'Edith Piaf': 'Chanson Francesa',
    'Jacques Brel': 'Chanson Francesa',
    'Jean-Claude Risset': 'Chanson Francesa',
    'Jean-Jacques Perrey': 'Chanson Francesa',
    'Justice': 'Chanson Francesa',
    'Luc Ferrari': 'Chanson Francesa',
    'Luis Maria Mucillo': 'Chanson Francesa',
    'MC Solaar': 'Chanson Francesa',
    'Phoenix': 'Chanson Francesa',
    'Pierre Schaeffer': 'Chanson Francesa',
    'Rina Ketty': 'Chanson Francesa',
    'Serge Gainsbourg': 'Chanson Francesa',
    # ── Música Indiana ────────────────────────────────────
    'Ananda Shankar': 'Música Indiana',
    'Meeta Ravindra': 'Música Indiana',
    'Ravi Shankar': 'Música Indiana',
    'Shivkumar Sharma/Brijbushan Ka': 'Música Indiana',
    # ── Música Sufi ───────────────────────────────────────
    'Nusrat Fateh Ali Khan': 'Música Sufi',
    # ── Reggae ────────────────────────────────────────────
    'Bad Brains': 'Reggae',
    'Bob Marley & The Wailers': 'Reggae',
    'Burning Spear': 'Reggae',
    'Gregory Isaacs': 'Reggae',
    'Johnny Clarke + The Aggrovators': 'Reggae',
    'Junior Byles': 'Reggae',
    'Junior Byles & Lee Perry': 'Reggae',
    'Lee Perry': 'Reggae',
    'Lee Perry & The Upsetters': 'Reggae',
    'Linval Thompson': 'Reggae',
    "Lloyd's All Stars": 'Reggae',
    'Madness': 'Reggae',
    'Manu Chao': 'Reggae',
    'Marcia Aitken': 'Reggae',
    'Marcia Griffiths': 'Reggae',
    'Peter Tosh': 'Reggae',
    'Scientist & Jammy & The Roots Radics': 'Reggae',
    'Scotty': 'Reggae',
    'UB40': 'Reggae',
    # ── Blues ─────────────────────────────────────────────
    'Al Kooper & Mike Bloomfield': 'Blues',
    'Albert King & Stevie Ray Vaughan': 'Blues',
    'Ali Farka Toure': 'Blues',
    'Aretha Franklin': 'Blues',
    'B. B. King': 'Blues',
    'Billie Holiday': 'Blues',
    'Blind Faith': 'Blues',
    'Bob Dylan': 'Blues',
    'Bonnie Raitt': 'Blues',
    'Box Of Frogs': 'Blues',
    'Buddy Emmons & Lenny Breau': 'Blues',
    'Canned Heat': 'Blues',
    'Captain Beefheart & His Magic Band': 'Blues',
    'Chris Farlowe': 'Blues',
    'Cream': 'Blues',
    'Cuby & Blizzards': 'Blues',
    'Electric Flag': 'Blues',
    'Ella Fitzgerald': 'Blues',
    'Elmore James': 'Blues',
    'Eric Clapton': 'Blues',
    'G. Love And Special Sauce': 'Blues',
    'James Brown': 'Blues',
    'Janis Joplin': 'Blues',
    'Jeff Beck': 'Blues',
    'Jimi Hendrix': 'Blues',
    'Jimmy Dawkins': 'Blues',
    'Jimmy Page': 'Blues',
    'Jimmy Page & Black Crowes': 'Blues',
    'Jimmy Rogers': 'Blues',
    'Joan Armatrading': 'Blues',
    'John Fogerty': 'Blues',
    'John Lee Hooker': 'Blues',
    'John Mayall & The Bluesbreakers': 'Blues',
    'Led Zeppelin': 'Blues',
    'Leonard Cohen': 'Blues',
    'Les Paul': 'Blues',
    'Milt Jackson/Wes Montgomery': 'Blues',
    'Muddy Waters': 'Blues',
    'Nina Simone': 'Blues',
    'Norah Jones': 'Blues',
    'Otis Redding': 'Blues',
    'Page & Plant': 'Blues',
    'Ray Charles': 'Blues',
    'Robert Plant': 'Blues',
    'Robert Plant & Alexis Korner': 'Blues',
    'Sarah Vaughan': 'Blues',
    'Shuggie Otis': 'Blues',
    'Smashing Pumpkins': 'Blues',
    'Solomon Burke': 'Blues',
    'Sonny Boy Williamson': 'Blues',
    'Sonny Boy Williamson & the Yardbirds': 'Blues',
    'Stevie Ray Vaughan': 'Blues',
    'Stevie Ray Vaughan And Double': 'Blues',
    'Van Morrison': 'Blues',
    'Wes Montgomery': 'Blues',
    'ZZ Top': 'Blues',
    # ── Blues Rock ────────────────────────────────────────
    'Lynyrd Skynyrd': 'Blues Rock',
    # ── Jazz ──────────────────────────────────────────────
    'Alma Cogan': 'Jazz',
    'Amy Winehouse': 'Jazz',
    'Andy Summers + Robert Fripp': 'Jazz',
    'Anita Baker': 'Jazz',
    'Anonymous Band': 'Jazz',
    'Art Blakey & The Jazz Messengers': 'Jazz',
    'Arthur Pryors Band': 'Jazz',
    'Astrud Gilberto': 'Jazz',
    'Baden Powell': 'Jazz',
    'Barry Adamson': 'Jazz',
    'Bebel Gilberto': 'Jazz',
    'Bill Evans Trio': 'Jazz',
    'Bill Frisell': 'Jazz',
    'Blood, Sweat & Tears': 'Jazz',
    'Brian Jackson/Gil Scott-Heron': 'Jazz',
    'Brian Setzer Orchestra': 'Jazz',
    'Brian Wilson': 'Jazz',
    'Buena Vista Social Club': 'Jazz',
    'Charles Mingus': 'Jazz',
    'Chet Atkins & Les Paul': 'Jazz',
    'Cleo Laine': 'Jazz',
    'Clifford Brown': 'Jazz',
    'David Behrman': 'Jazz',
    'Dom Um Romao': 'Jazz',
    'Eddie Lang': 'Jazz',
    'Eddie Lang / Joe Venuti': 'Jazz',
    'Egberto Gismonti': 'Jazz',
    'Eric Dolphy': 'Jazz',
    'Erroll Garner': 'Jazz',
    'Erykah Badu': 'Jazz',
    'Eve Boswell': 'Jazz',
    'Frank Banta': 'Jazz',
    'Fred Van Eps': 'Jazz',
    'Gary Burton': 'Jazz',
    'George Benson': 'Jazz',
    'George Russell Sextet': 'Jazz',
    'Ginga Trio': 'Jazz',
    'Glenn Miller': 'Jazz',
    'Graeme Bell And His Australian Jazz Band': 'Jazz',
    'Herbie Hancock': 'Jazz',
    'Hugh Masekela': 'Jazz',
    'Humphrey Lyttelton & His Band': 'Jazz',
    'Ian Wallace': 'Jazz',
    'Jimmy Smith': 'Jazz',
    'Jimmy Smith & Wes Montgomery': 'Jazz',
    'Joao Gilberto': 'Jazz',
    'Joe Pass': 'Jazz',
    'John Coltrane': 'Jazz',
    'John McLaughlin & The Mahavishnu Orchestra': 'Jazz',
    'John Zorn': 'Jazz',
    'Jon Hassell': 'Jazz',
    'Joseph Moskovitz': 'Jazz',
    'Kashmere Stage Band': 'Jazz',
    'Keith Jarrett': 'Jazz',
    'Lee Morgan Quintet': 'Jazz',
    'Lenny Breau': 'Jazz',
    'Louis Prima': 'Jazz',
    'Machito': 'Jazz',
    'Mahavishnu Orchestra': 'Jazz',
    'Max Geldray': 'Jazz',
    'Mike Ladd': 'Jazz',
    'Mike Melvoin': 'Jazz',
    'Miles Davis': 'Jazz',
    'Neil Sedaka': 'Jazz',
    'Okko': 'Jazz',
    'Oldies; swing; crooners': 'Jazz',
    'Ornette Coleman': 'Jazz',
    'Oscar Peterson': 'Jazz',
    'Paul Winter': 'Jazz',
    'Penguin Cafe Orchestra': 'Jazz',
    'Pietro Deiro': 'Jazz',
    'Queen Latifah': 'Jazz',
    'Quincy Jones': 'Jazz',
    'Ray Crawford': 'Jazz',
    'Raymond Scott': 'Jazz',
    'Roberto Menescal': 'Jazz',
    'Sabu Martinez': 'Jazz',
    'Sade': 'Jazz',
    'Sergio Mendes & Bossa Rio': 'Jazz',
    'Shirley Bassey': 'Jazz',
    "Simply the Best of the 60's": 'Jazz',
    'Sinatra Frank': 'Jazz',
    'Sinatra, Frank': 'Jazz',
    'Soft Machine': 'Jazz',
    'Som Imaginário': 'Jazz',
    'Sonny Rollins': 'Jazz',
    'Sousa Band': 'Jazz',
    'Stan Getz': 'Jazz',
    'Stan Getz & Charlie Byrd': 'Jazz',
    'Stan Getz & João Gilberto': 'Jazz',
    'Steely Dan': 'Jazz',
    'The Alberts': 'Jazz',
    'The Temperance Seven': 'Jazz',
    'Ute Lemper': 'Jazz',
    'Vess Ossman': 'Jazz',
    'Victor Dance Orchestra': 'Jazz',
    'Victor Military Band': 'Jazz',
    'Victor Minstrels': 'Jazz',
    'Vince Guaraldi Trio': 'Jazz',
    'Wayne Shorter': 'Jazz',
    'Weather Report': 'Jazz',
    'Zimbo Trio': 'Jazz',
    # ── Jazz/Swing ────────────────────────────────────────
    'America': 'Jazz/Swing',
    'Bernard Cribbins': 'Jazz/Swing',
    'Billy J Kramer with The Dakotas': 'Jazz/Swing',
    'Billy Preston': 'Jazz/Swing',
    'Charlie Drake': 'Jazz/Swing',
    'Cheap Trick': 'Jazz/Swing',
    'Cilla Black': 'Jazz/Swing',
    'Dick James': 'Jazz/Swing',
    'Flanders & Swann': 'Jazz/Swing',
    'Flanders and Swann': 'Jazz/Swing',
    'Gary Brooker': 'Jazz/Swing',
    'Gerry & The Pacemakers': 'Jazz/Swing',
    'Gerry and The Pacemakers': 'Jazz/Swing',
    'Jim Dale': 'Jazz/Swing',
    'Jimmy Shand': 'Jazz/Swing',
    'Jimmy Webb': 'Jazz/Swing',
    'John Scott': 'Jazz/Swing',
    'John Williams': 'Jazz/Swing',
    'Jose Carreras': 'Jazz/Swing',
    'Kenneth McKellar': 'Jazz/Swing',
    'Kenny Rogers': 'Jazz/Swing',
    'Mandy Miller': 'Jazz/Swing',
    'Matt Monro': 'Jazz/Swing',
    'Matt Monroe': 'Jazz/Swing',
    'Nadia Gray': 'Jazz/Swing',
    'Paul McCartney': 'Jazz/Swing',
    'Paul McCartney & Michael Jackson': 'Jazz/Swing',
    'Paul McCartney & Stevie Wonder': 'Jazz/Swing',
    'Paul McCartney & Wings': 'Jazz/Swing',
    'Peter Sellers': 'Jazz/Swing',
    'Peter Sellers & Sophia Loren': 'Jazz/Swing',
    'Ray Cathode': 'Jazz/Swing',
    'Rolf Harris': 'Jazz/Swing',
    'Ron Goodwin': 'Jazz/Swing',
    'Ron Goodwin & His Concert Orchestra': 'Jazz/Swing',
    'Ron Goodwin & His Orchestra': 'Jazz/Swing',
    'Seatrain': 'Jazz/Swing',
    'Spike Milligan': 'Jazz/Swing',
    'Stackridge': 'Jazz/Swing',
    'Terry Scott': 'Jazz/Swing',
    'The Action': 'Jazz/Swing',
    'The Beatles': 'Jazz/Swing',
    'The Dakotas': 'Jazz/Swing',
    'The Fourmost': 'Jazz/Swing',
    "The King's Singers": 'Jazz/Swing',
    'The Oldies; swing; crooners Orchestra': 'Jazz/Swing',
    'The Southlanders': 'Jazz/Swing',
    'The Vipers': 'Jazz/Swing',
    'The Vipers Skiffle Group': 'Jazz/Swing',
    'Tom Jones': 'Jazz/Swing',
    'Tommy Reilly': 'Jazz/Swing',
    'Ultravox': 'Jazz/Swing',
    # ── Soul ──────────────────────────────────────────────
    'Adele': 'Soul',
    'Al Green': 'Soul',
    'Alex Cima': 'Soul',
    'Bobby Womack': 'Soul',
    'Chic': 'Soul',
    'Christina Aguilera': 'Soul',
    'Common': 'Soul',
    'Curtis Mayfield': 'Soul',
    'Earth, Wind & Fire': 'Soul',
    'George Michael': 'Soul',
    'Gnarls Barkley': 'Soul',
    'Isaac Hayes': 'Soul',
    'Jackson Five': 'Soul',
    'Laura Nyro': 'Soul',
    'Lauryn Hill': 'Soul',
    'Mariah Carey': 'Soul',
    'Marvin Gaye': 'Soul',
    'Michael Jackson': 'Soul',
    'Misia': 'Soul',
    'Motown': 'Soul',
    'Neneh Cherry': 'Soul',
    'OutKast': 'Soul',
    'Parliament': 'Soul',
    'Prince': 'Soul',
    'Sam Cooke': 'Soul',
    'Simply Red': 'Soul',
    'Sister Sledge': 'Soul',
    'Sly & The Family Stone': 'Soul',
    'Sly & the Family Stone': 'Soul',
    'Stevie Wonder': 'Soul',
    'War': 'Soul',
    # ── Soul/Funk ─────────────────────────────────────────
    'A Tribe Called Quest': 'Soul/Funk',
    'Grandmaster Flash & the Furious Five': 'Soul/Funk',
    'Jamiroquai': 'Soul/Funk',
    'Lenny Kravitz': 'Soul/Funk',
    'Living Colour': 'Soul/Funk',
    'Ozomatli': 'Soul/Funk',
    'Red Hot Chili Peppers': 'Soul/Funk',
    # ── R&B ───────────────────────────────────────────────
    'Bobby Lewis': 'R&B',
    'Janet Jackson': 'R&B',
    'Justin Timberlake': 'R&B',
    'LL Cool J': 'R&B',
    'Louie Lymon & The Teenchords': 'R&B',
    'Missy Elliott': 'R&B',
    'Ms. Dynamite': 'R&B',
    'Starlighters': 'R&B',
    # ── Hip-Hop/Rap ───────────────────────────────────────
    '2Pac': 'Hip-Hop/Rap',
    'Beastie Boys': 'Hip-Hop/Rap',
    'Cypress Hill': 'Hip-Hop/Rap',
    'Eminem': 'Hip-Hop/Rap',
    'Gang Starr': 'Hip-Hop/Rap',
    'Gorillaz': 'Hip-Hop/Rap',
    'Ice Cube': 'Hip-Hop/Rap',
    'Ice-T': 'Hip-Hop/Rap',
    'Jay-Z': 'Hip-Hop/Rap',
    'Jeru the Damaja': 'Hip-Hop/Rap',
    'Jungle Brothers': 'Hip-Hop/Rap',
    'N.W.A': 'Hip-Hop/Rap',
    'Nas': 'Hip-Hop/Rap',
    'PeteRock & C.L. Smooth': 'Hip-Hop/Rap',
    'Prodigy': 'Hip-Hop/Rap',
    'Public Enemy': 'Hip-Hop/Rap',
    'Raekwon': 'Hip-Hop/Rap',
    'Run-D.M.C.': 'Hip-Hop/Rap',
    'Snoop Doggy Dogg': 'Hip-Hop/Rap',
    "Stereo MC's": 'Hip-Hop/Rap',
    'The Streets': 'Hip-Hop/Rap',
    'Wu-Tang Clan': 'Hip-Hop/Rap',
    # ── World Music ───────────────────────────────────────
    'Angelique Kidjo': 'World Music',
    'Baaba Maal': 'World Music',
    'Cheb Khaled': 'World Music',
    'Ladysmith Black Mambazo': 'World Music',
    'Miriam Makeba': 'World Music',
    'Rahul Dev Burman': 'World Music',
    'Santa Esmeralda': 'World Music',
    'Santana': 'World Music',
    'Willie Colón & Rubén Blades': 'World Music',
    "Youssou N'dour": 'World Music',
    # ── Heavy Metal ───────────────────────────────────────
    'AC/DC': 'Heavy Metal',
    'Anthrax': 'Heavy Metal',
    'Black Sabbath': 'Heavy Metal',
    'Cathedral': 'Heavy Metal',
    "Guns N' Roses": 'Heavy Metal',
    'HanoiRocks': 'Heavy Metal',
    'Incubus': 'Heavy Metal',
    'Iron Maiden': 'Heavy Metal',
    'Judas Priest': 'Heavy Metal',
    'Korn': 'Heavy Metal',
    'Limp Bizkit': 'Heavy Metal',
    'Linkin Park': 'Heavy Metal',
    'Marilyn Manson': 'Heavy Metal',
    'Meatloaf': 'Heavy Metal',
    'Megadeth': 'Heavy Metal',
    'Metallica': 'Heavy Metal',
    'Ministry': 'Heavy Metal',
    'Motley Crue': 'Heavy Metal',
    'Motörhead': 'Heavy Metal',
    'Mr. Bungle': 'Heavy Metal',
    'Napalm Death': 'Heavy Metal',
    'Nine Inch Nails': 'Heavy Metal',
    'Oui Madame': 'Heavy Metal',
    'Pantera': 'Heavy Metal',
    'Queens Of The Stone Age': 'Heavy Metal',
    'Sepultura': 'Heavy Metal',
    'Slayer': 'Heavy Metal',
    'Slipknot': 'Heavy Metal',
    'System of a Down': 'Heavy Metal',
    'Van Halen': 'Heavy Metal',
    'Young Gods': 'Heavy Metal',
    # ── Hard Rock ─────────────────────────────────────────
    'Aerosmith': 'Hard Rock',
    'Alice Cooper': 'Hard Rock',
    'Bad Company': 'Hard Rock',
    'Blue Cheer': 'Hard Rock',
    'Bon Jovi': 'Hard Rock',
    'Boston': 'Hard Rock',
    'Hawkwind': 'Hard Rock',
    'Iron Butterfly': 'Hard Rock',
    'Kiss': 'Hard Rock',
    'MC5': 'Hard Rock',
    'Mott The Hoople': 'Hard Rock',
    'Screaming Lord Sutch': 'Hard Rock',
    # ── Grunge ────────────────────────────────────────────
    'Alice In Chains': 'Grunge',
    'Everclear': 'Grunge',
    'Gumball': 'Grunge',
    'Hole': 'Grunge',
    "Jane's Addiction": 'Grunge',
    'L7': 'Grunge',
    'Live': 'Grunge',
    'Meat Puppets': 'Grunge',
    'Melvins': 'Grunge',
    'Mudhoney': 'Grunge',
    'Nirvana': 'Grunge',
    'Pearl Jam': 'Grunge',
    'Screaming Trees': 'Grunge',
    'Silverchair': 'Grunge',
    'Soundgarden': 'Grunge',
    'Stone Temple Pilots': 'Grunge',
    # ── Punk ──────────────────────────────────────────────
    'Adam & The Ants': 'Punk',
    'As Mercenarias': 'Punk',
    'As Mercenárias': 'Punk',
    'Big Black': 'Punk',
    'Big Star': 'Punk',
    'Billy Idol': 'Punk',
    'Black Flag': 'Punk',
    'Blondie': 'Punk',
    'Butthole Surfers': 'Punk',
    'Buzzcocks': 'Punk',
    'Circle Jerks': 'Punk',
    'Gang of Four': 'Punk',
    'Green Day': 'Punk',
    'Hüsker Dü': 'Punk',
    'Ian Dury': 'Punk',
    'Iggy & The Stooges': 'Punk',
    'Iggy Pop': 'Punk',
    'Magazine': 'Punk',
    'Mekons': 'Punk',
    'Minor Threat': 'Punk',
    'Minutemen': 'Punk',
    'Mission Of Burma': 'Punk',
    'Monks': 'Punk',
    'New York Dolls': 'Punk',
    'Offspring': 'Punk',
    'Patti Smith': 'Punk',
    'Public Image Ltd.': 'Punk',
    'Rocket From The Crypt': 'Punk',
    'Rollins Band': 'Punk',
    'Siouxsie & The Banshees': 'Punk',
    'Sleater-Kinney': 'Punk',
    'Social Distortion': 'Punk',
    "Sonic's Rendezvous Band": 'Punk',
    'Suicide': 'Punk',
    'Wire': 'Punk',
    'X-Ray Spex': 'Punk',
    # ── Rockabilly ────────────────────────────────────────
    'Buddy Holly & The Picks': 'Rockabilly',
    'Buddy Knox': 'Rockabilly',
    'Carl Perkins': 'Rockabilly',
    'Eddie Cochran': 'Rockabilly',
    'Elvis Presley': 'Rockabilly',
    'Jerry Lee Lewis': 'Rockabilly',
    'Johnny Kidd & The Pirates': 'Rockabilly',
    'Little Richard': 'Rockabilly',
    'Roy Orbison': 'Rockabilly',
    'Scotty McKay Quintet': 'Rockabilly',
    'Sparkle Moore With Dan Belloc And His Orchestra': 'Rockabilly',
    'Stray Cats': 'Rockabilly',
    # ── Rock Psicodélico ──────────────────────────────────
    'Arnaldo Baptista': 'Rock Psicodélico',
    'Beaver & Krause': 'Rock Psicodélico',
    'Blues Magoos': 'Rock Psicodélico',
    'Bruce Haack': 'Rock Psicodélico',
    'Caleb': 'Rock Psicodélico',
    'Can': 'Rock Psicodélico',
    'Chocolate Watchband': 'Rock Psicodélico',
    'Country Joe & The Fish': 'Rock Psicodélico',
    'Electric Prunes': 'Rock Psicodélico',
    'Jefferson Airplane': 'Rock Psicodélico',
    'Jefferson Starship': 'Rock Psicodélico',
    "John's Children": 'Rock Psicodélico',
    'Julian Cope': 'Rock Psicodélico',
    'Lilys': 'Rock Psicodélico',
    'Los Chijuas': 'Rock Psicodélico',
    'Lothar And The Hand People': 'Rock Psicodélico',
    'Love': 'Rock Psicodélico',
    'Lyme And Cybelle': 'Rock Psicodélico',
    'MGMT': 'Rock Psicodélico',
    'Max Frost & the Troopers': 'Rock Psicodélico',
    'Michael Yonkers Band': 'Rock Psicodélico',
    'Mickey Finn': 'Rock Psicodélico',
    'Moby Grape': 'Rock Psicodélico',
    'Mouse & The Traps': 'Rock Psicodélico',
    'Neil Christian': 'Rock Psicodélico',
    'Neu!': 'Rock Psicodélico',
    'New Colo': 'Rock Psicodélico',
    'Os Mutantes': 'Rock Psicodélico',
    'Pink Floyd': 'Rock Psicodélico',
    'Renato Mendes': 'Rock Psicodélico',
    'Roger Waters': 'Rock Psicodélico',
    'Rogerio Duprat': 'Rock Psicodélico',
    'Rogério Duprat': 'Rock Psicodélico',
    'Secos & Molhados': 'Rock Psicodélico',
    'Spirit': 'Rock Psicodélico',
    'Spiritualized': 'Rock Psicodélico',
    'Steppenwolf': 'Rock Psicodélico',
    'Sérgio Dias': 'Rock Psicodélico',
    'Vanilla Fudge': 'Rock Psicodélico',
    'White Noise': 'Rock Psicodélico',
    # ── Shoegaze ──────────────────────────────────────────
    'Catherine Wheel': 'Shoegaze',
    'Chapterhouse': 'Shoegaze',
    'Cocteau Twins': 'Shoegaze',
    'Curve': 'Shoegaze',
    'Enchantments': 'Shoegaze',
    'Lush': 'Shoegaze',
    'Moose': 'Shoegaze',
    'My Bloody Valentine': 'Shoegaze',
    'Pale Saints': 'Shoegaze',
    'Ride': 'Shoegaze',
    'Slowdive': 'Shoegaze',
    'Velocity Girl': 'Shoegaze',
    # ── Krautrock ─────────────────────────────────────────
    'Holger Czukay': 'Krautrock',
    'Klaus Schulze': 'Krautrock',
    # ── Art Rock ──────────────────────────────────────────
    'Brian Eno': 'Art Rock',
    'Queen': 'Art Rock',
    # ── Rock Progressivo ──────────────────────────────────
    '10CC': 'Rock Progressivo',
    'Banco Del Mutuo Soccorso': 'Rock Progressivo',
    'Casa Das Maquinas': 'Rock Progressivo',
    'Chris Squire': 'Rock Progressivo',
    'Emerson, Lake & Palmer': 'Rock Progressivo',
    'Genesis': 'Rock Progressivo',
    'Gentle Giant': 'Rock Progressivo',
    'Jethro Tull': 'Rock Progressivo',
    'Jon Anderson': 'Rock Progressivo',
    'King Crimson': 'Rock Progressivo',
    'Luigi Ceccarelli': 'Rock Progressivo',
    'Luigi Russolo, Antonio Russolo': 'Rock Progressivo',
    'Mike Oldfield': 'Rock Progressivo',
    'O Terco': 'Rock Progressivo',
    'Rick Wakeman': 'Rock Progressivo',
    'Rick van der Linden': 'Rock Progressivo',
    'Robert Wyatt': 'Rock Progressivo',
    'Rush': 'Rock Progressivo',
    'SAECULA SAECULORUM': 'Rock Progressivo',
    'Sagrado Coração Da Terra': 'Rock Progressivo',
    'Som Nosso De Cada Dia': 'Rock Progressivo',
    'Steve Hackett': 'Rock Progressivo',
    'Steve Howe': 'Rock Progressivo',
    'Supertramp': 'Rock Progressivo',
    'Yes': 'Rock Progressivo',
    # ── New Wave ──────────────────────────────────────────
    'ABC': 'New Wave',
    'Adrian Belew': 'New Wave',
    'Culture Club': 'New Wave',
    'Cyndi Lauper': 'New Wave',
    'Elvis Costello': 'New Wave',
    'Eurythmics': 'New Wave',
    'Gary Numan': 'New Wave',
    'Haircut 100': 'New Wave',
    'Heaven 17': 'New Wave',
    'Jah Wobble': 'New Wave',
    'Japan': 'New Wave',
    'Pet Shop Boys': 'New Wave',
    'Scritti Politti': 'New Wave',
    'Simple Minds': 'New Wave',
    'Soft Cell': 'New Wave',
    'Sparks': 'New Wave',
    'Style Council': 'New Wave',
    'U2': 'New Wave',
    'XTC': 'New Wave',
    'a-ha': 'New Wave',
    # ── Britpop ───────────────────────────────────────────
    'Ash': 'Britpop',
    'Blur': 'Britpop',
    'Coldplay': 'Britpop',
    'Cornershop': 'Britpop',
    'Elastica': 'Britpop',
    'Kaiser Chiefs': 'Britpop',
    'Manic Street Preachers': 'Britpop',
    'Muse': 'Britpop',
    'Oasis': 'Britpop',
    'Paul Weller': 'Britpop',
    'Pulp': 'Britpop',
    'Richard Hawley': 'Britpop',
    'Robbie Williams': 'Britpop',
    'Shack': 'Britpop',
    'Suede': 'Britpop',
    'Supergrass': 'Britpop',
    # ── Blues Rock ────────────────────────────────────────
    'Lynyrd Skynyrd': 'Blues Rock',
    # ── Rock Alternativo ──────────────────────────────────
    'Aimee Mann': 'Rock Alternativo',
    'Alanis Morissette': 'Rock Alternativo',
    'American Music Club': 'Rock Alternativo',
    'Antony And The Johnsons': 'Rock Alternativo',
    'Arcade Fire': 'Rock Alternativo',
    'Arctic Monkeys': 'Rock Alternativo',
    'Associates': 'Rock Alternativo',
    'Badly Drawn Boy': 'Rock Alternativo',
    'Bauhaus': 'Rock Alternativo',
    'Beck': 'Rock Alternativo',
    'Belle & Sebastian': 'Rock Alternativo',
    'Björk': 'Rock Alternativo',
    'Black Kids': 'Rock Alternativo',
    'Blake Babies': 'Rock Alternativo',
    'Blue Nile': 'Rock Alternativo',
    'Calexico': 'Rock Alternativo',
    'Crowded House': 'Rock Alternativo',
    'Echo & The Bunnymen': 'Rock Alternativo',
    'Edward Sharpe & The Magnetic Zeros': 'Rock Alternativo',
    'Eels': 'Rock Alternativo',
    'Everything But the Girl': 'Rock Alternativo',
    'Garbage': 'Rock Alternativo',
    'Giant Sand': 'Rock Alternativo',
    'Girls Against Boys': 'Rock Alternativo',
    'Glass Animals': 'Rock Alternativo',
    'Gotye': 'Rock Alternativo',
    'Grant Lee Buffalo': 'Rock Alternativo',
    'Guided By Voices': 'Rock Alternativo',
    'Happy Mondays': 'Rock Alternativo',
    'Jeff Buckley': 'Rock Alternativo',
    'Joy Division': 'Rock Alternativo',
    'Kate Bush': 'Rock Alternativo',
    'Killing Joke': 'Rock Alternativo',
    'Kings Of Leon': 'Rock Alternativo',
    'Klaxons': 'Rock Alternativo',
    'Lambchop': 'Rock Alternativo',
    'Le Tigre': 'Rock Alternativo',
    'Lee Ranaldo': 'Rock Alternativo',
    'Liars': 'Rock Alternativo',
    'Lightning Bolt': 'Rock Alternativo',
    'Liz Phair': 'Rock Alternativo',
    'Lloyd Cole': 'Rock Alternativo',
    'Maximo Park': 'Rock Alternativo',
    'Mercury Rev': 'Rock Alternativo',
    'Morrissey': 'Rock Alternativo',
    'New Order': 'Rock Alternativo',
    'Nick Cave': 'Rock Alternativo',
    'Nick Cave & The Bad Seeds': 'Rock Alternativo',
    'Nick Cave & the Bad Seeds': 'Rock Alternativo',
    'Nico': 'Rock Alternativo',
    'P.J. Harvey': 'Rock Alternativo',
    'Pavement': 'Rock Alternativo',
    'Pere Ubu': 'Rock Alternativo',
    'Peter, Bjorn and John': 'Rock Alternativo',
    'Pixies': 'Rock Alternativo',
    'R.E.M.': 'Rock Alternativo',
    'Radiohead': 'Rock Alternativo',
    'Rage Against The Machine': 'Rock Alternativo',
    'Rufus Wainwright': 'Rock Alternativo',
    'Sebadoh': 'Rock Alternativo',
    'Shells': 'Rock Alternativo',
    'Sheryl Crow': 'Rock Alternativo',
    'Sigur Rós': 'Rock Alternativo',
    'Silver Jews': 'Rock Alternativo',
    "Sinead O'Connor": 'Rock Alternativo',
    'Slint': 'Rock Alternativo',
    'Sonic Youth': 'Rock Alternativo',
    'Stereolab': 'Rock Alternativo',
    'Sufjan Stevens': 'Rock Alternativo',
    'Sugar': 'Rock Alternativo',
    'Superchunk': 'Rock Alternativo',
    'Suzanne Vega': 'Rock Alternativo',
    'Vampire Weekend': 'Rock Alternativo',
    'Violent Femmes': 'Rock Alternativo',
    'Weezer': 'Rock Alternativo',
    'Wilco': 'Rock Alternativo',
    'Yeah Yeah Yeahs': 'Rock Alternativo',
    'Yo La Tengo': 'Rock Alternativo',
    'Zwan': 'Rock Alternativo',
    # ── Indie ─────────────────────────────────────────────
    'Billy Bragg & Wilco': 'Indie',
    'Cut Copy': 'Indie',
    'Elliott Smith': 'Indie',
    'Joanna Newsom': 'Indie',
    'LCD Soundsystem': 'Indie',
    'Mumford & Sons': 'Indie',
    'Nick Drake': 'Indie',
    'Primal Scream': 'Indie',
    'Ryan Adams': 'Indie',
    'Saint Etienne': 'Indie',
    # ── Eletrônico ────────────────────────────────────────
    '808 State': 'Eletrônico',
    'Air': 'Eletrônico',
    'Alistair Macdonald': 'Eletrônico',
    'Alvin Curran': 'Eletrônico',
    'Alvin Lucier': 'Eletrônico',
    'Aphex Twin': 'Eletrônico',
    'Basement Jaxx': 'Eletrônico',
    'Bernard Parmegiani': 'Eletrônico',
    'Boards of Canada': 'Eletrônico',
    'Bob Sinclar': 'Eletrônico',
    'Brian Eno & David Byrne': 'Eletrônico',
    'Britney Spears': 'Eletrônico',
    'Carlos Cerana': 'Eletrônico',
    'Charles Dodge': 'Eletrônico',
    'ClaraRockmore': 'Eletrônico',
    'Coldcut': 'Eletrônico',
    'David Tudor': 'Eletrônico',
    'Elio Martusciello': 'Eletrônico',
    'Francois Bayle': 'Eletrônico',
    'George Harrison': 'Eletrônico',
    'Gershon Kingsley': 'Eletrônico',
    'Giorgio Moroder': 'Eletrônico',
    'Goldfrapp': 'Eletrônico',
    'Goldie': 'Eletrônico',
    'Gordon Mumma': 'Eletrônico',
    'Gotan Project': 'Eletrônico',
    'Henri Pousseur': 'Eletrônico',
    'Herbert Eimert': 'Eletrônico',
    'Hercules And Love Affair': 'Eletrônico',
    'Hugh Le Caine': 'Eletrônico',
    'Hugo Montenegro': 'Eletrônico',
    'Iannis Xenakis': 'Eletrônico',
    'Jean Michel Jarre': 'Eletrônico',
    'Jets': 'Eletrônico',
    'John Baker': 'Eletrônico',
    'John Cage': 'Eletrônico',
    'John Chowning': 'Eletrônico',
    'Joji Yuasa': 'Eletrônico',
    'Jonny Greenwood': 'Eletrônico',
    'Karlheinz Stockhausen': 'Eletrônico',
    'Konrad Boehmer': 'Eletrônico',
    'Kraftwerk': 'Eletrônico',
    'LTJ Bukem': 'Eletrônico',
    'La Monte Young': 'Eletrônico',
    'Ladytron': 'Eletrônico',
    'Laurie Spiegel': 'Eletrônico',
    'Leftfield': 'Eletrônico',
    'Les Rythmes Digitales': 'Eletrônico',
    'Louis and Bebe Barron': 'Eletrônico',
    'Lydia Kavina': 'Eletrônico',
    'MEV': 'Eletrônico',
    'MJ Cole': 'Eletrônico',
    'Madonna': 'Eletrônico',
    'Madredeus': 'Eletrônico',
    'Magnus Lindberg': 'Eletrônico',
    'Mario Verandi': 'Eletrônico',
    'Marty Gold': 'Eletrônico',
    'Maryanne Amacher': 'Eletrônico',
    'Massive Attack': 'Eletrônico',
    'Michael Jarrell': 'Eletrônico',
    'Mike Hankinson': 'Eletrônico',
    'Milton Babbitt': 'Eletrônico',
    'Moby': 'Eletrônico',
    'Moog Party Time': 'Eletrônico',
    'Mort Garson': 'Eletrônico',
    'Morton Subotnick': 'Eletrônico',
    'Mylo': 'Eletrônico',
    'Naked Eyes': 'Eletrônico',
    'Nam June Paik': 'Eletrônico',
    'Nightmares On Wax': 'Eletrônico',
    'Nitin Sawhney': 'Eletrônico',
    'Oskar Sala': 'Eletrônico',
    'Otto Luening': 'Eletrônico',
    'Paddy Kingsland (The BBC Radiophonic Workshop)': 'Eletrônico',
    'Paul D. Miller aka DJ Spooky That Subliminal Kid': 'Eletrônico',
    'Paul Lansky': 'Eletrônico',
    'Pauline Oliveros': 'Eletrônico',
    'Perrey-Kingsley': 'Eletrônico',
    'Portishead': 'Eletrônico',
    'Red Snapper': 'Eletrônico',
    'Ricardo Mandolini': 'Eletrônico',
    'Richard Hayman': 'Eletrônico',
    'Richard Hayman & Walter Sear': 'Eletrônico',
    'Richard Maxfield': 'Eletrônico',
    'Rick Powell': 'Eletrônico',
    'Robert Ashley': 'Eletrônico',
    'Ruth White': 'Eletrônico',
    'Ryoji Ikeda': 'Eletrônico',
    'SUBA': 'Eletrônico',
    'Sabres of Paradise': 'Eletrônico',
    'Scissor Sisters': 'Eletrônico',
    'Steve Reich': 'Eletrônico',
    'Survival Research Laboratories': 'Eletrônico',
    'Terry Riley': 'Eletrônico',
    'Tod Dockstader': 'Eletrônico',
    'Underworld': 'Eletrônico',
    'Vangelis': 'Eletrônico',
    'Vladimir Ussachevsky': 'Eletrônico',
    'Walter E. Sear': 'Eletrônico',
    'Walter Ruttman': 'Eletrônico',
    'Weird Al Yankovic & Wendy Carlos': 'Eletrônico',
    'William Orbit': 'Eletrônico',
    # ── House ─────────────────────────────────────────────
    'Lulu': 'House',
    'Orson Welles': 'House',
    # ── Experimental ──────────────────────────────────────
    'John Cale': 'Experimental',
    'Lou Reed': 'Experimental',
    'Scott Walker': 'Experimental',
    # ── Rock ──────────────────────────────────────────────
    'A Bolha': 'Rock',
    'Al Stewart': 'Rock',
    'Atlantics': 'Rock',
    'BackBeat Band': 'Rock',
    'Backbeat Band': 'Rock',
    'Blue Rondos': 'Rock',
    'Bob Seger': 'Rock',
    'Bobby Bare': 'Rock',
    'Bruce Springsteen': 'Rock',
    'Bryan Ferry': 'Rock',
    'Buddy Baker': 'Rock',
    'Buffalo Springfield': 'Rock',
    'Carole King': 'Rock',
    'Carrols Mood': 'Rock',
    'Cat Stevens': 'Rock',
    'Chad & Jeremy': 'Rock',
    'Chicago': 'Rock',
    'Chitãozinho & Xororó/Cabal': 'Rock',
    'Chitãozinho & Xororó/Ivete Sangalo/Margareth Menezes': 'Rock',
    'Chitãozinho & Xororó/Roupa Nova': 'Rock',
    'Clusters': 'Rock',
    'Coverdale & Page': 'Rock',
    'Creedence Clearwater Revival': 'Rock',
    'Crosby, Stills, Nash & Young': 'Rock',
    'Eagles': 'Rock',
    'Edsels': 'Rock',
    'Elton John': 'Rock',
    'George Baker Selection': 'Rock',
    'Harry Nilsson': 'Rock',
    'Ira!': 'Rock',
    'Jake Holmes': 'Rock',
    'James Taylor': 'Rock',
    'Joelho De Porco': 'Rock',
    'Joey Dee And The Starlighters': 'Rock',
    'John Lennon': 'Rock',
    'John Paul Jones': 'Rock',
    'Johnny Cash': 'Rock',
    'Larry Adler featuring Peter Gabriel': 'Rock',
    'Les Jaguars': 'Rock',
    'Liu e Léu': 'Rock',
    'Made In Brazil': 'Rock',
    'Marcus': 'Rock',
    'Marianne Faithfull': 'Rock',
    'Mellotones': 'Rock',
    'Mickie Most': 'Rock',
    'Nanná Millano': 'Rock',
    'Neil Young': 'Rock',
    'P.J. Proby': 'Rock',
    'Paul McCartney & The Wings': 'Rock',
    'Paul Revere & The Raiders': 'Rock',
    'Paul Simon': 'Rock',
    'Peter Frampton': 'Rock',
    'Peter Gabriel': 'Rock',
    'Poeta e Trovador': 'Rock',
    'Rainbows': 'Rock',
    'Randy Newman': 'Rock',
    'Richard & Linda Thompson': 'Rock',
    'Ringo Starr': 'Rock',
    'Rita Lee': 'Rock',
    'Rod Stewart': 'Rock',
    'Roxy Music': 'Rock',
    'Roy Harper & Jimmy Page': 'Rock',
    'Scientific American': 'Rock',
    'Simon & Garfunkel': 'Rock',
    'Slade': 'Rock',
    'Socrate': 'Rock',
    'Stephen Stills': 'Rock',
    'Steve Earle': 'Rock',
    'Sá, Rodrix & Guarabyra': 'Rock',
    'Unknown': 'Rock',
    # ── MPB ───────────────────────────────────────────────
    'Bacamarte': 'MPB',
    'Caetano Veloso': 'MPB',
    'Carlinhos Brown': 'MPB',
    'Chico Buarque': 'MPB',
    'Dorival Caymmi': 'MPB',
    'Gilberto Gil': 'MPB',
    'Gilberto Gil & Jorge Ben': 'MPB',
    'Maria Bethânia': 'MPB',
    'Momento Quatro': 'MPB',
    'Nara Leao': 'MPB',
    'O Seis': 'MPB',
    'Ronnie Von': 'MPB',
    'Vinícius De Moraes': 'MPB',
    'Wanda Sa': 'MPB',
    # ── Disco ─────────────────────────────────────────────
    'Abba': 'Disco',
    'Bee Gees': 'Disco',
    # ── Pop ───────────────────────────────────────────────
    'George Ellias': 'Pop',
    'John Travolta & Olivia Newton': 'Pop',
    'K.D. Lang': 'Pop',
    # ── Country ───────────────────────────────────────────
    'Buck Owens': 'Country',
    'Emmylou Harris': 'Country',
    'Gene Clark': 'Country',
    'George Jones': 'Country',
    'Gillian Welch': 'Country',
    'Hank Williams': 'Country',
    'Joe Ely': 'Country',
    'John Prine': 'Country',
    'Loretta Lynn': 'Country',
    'Lucinda Williams': 'Country',
    'Marty Robbins': 'Country',
    'Merle Haggard': 'Country',
    'Merle Travis': 'Country',
    'Nanci Griffith': 'Country',
    'Nitty Gritty Dirt Band': 'Country',
    "Ramblin' Jack Elliott": 'Country',
    'Waylon Jennings': 'Country',
    'Willie Nelson': 'Country',
    # ── Folk ──────────────────────────────────────────────
    'Joan Baez': 'Folk',
    'John Martyn': 'Folk',
    'Joni Mitchell': 'Folk',
    'Leo Kottke': 'Folk',
    'Pentangle': 'Folk',
    # ── Clássico ──────────────────────────────────────────
    'London Philharmonic Orchestra': 'Clássico',
    # ── Instrumental ──────────────────────────────────────
    'Adrian Legg': 'Instrumental',
    'Michael Hedges': 'Instrumental',
    # ── Trilha Sonora ─────────────────────────────────────
    'Masato Nakamura': 'Trilha Sonora',
}



def parse_key(tom_musical: str) -> tuple[str, str]:
    """'A minor' → ('A', 'minor') | 'C# major' → ('C#', 'major')"""
    parts = tom_musical.strip().split()
    if len(parts) >= 2 and parts[-1].lower() in ("minor", "major"):
        return " ".join(parts[:-1]), parts[-1].lower()
    return tom_musical.strip(), ""


def safe_float(v: str) -> str:
    """Retorna string numérica válida ou vazio."""
    try:
        f = float(v)
        if not (f == f):  # NaN check
            return ""
        return str(f)
    except (ValueError, TypeError):
        return ""


def transform(src: str, dst: str) -> None:
    skipped_status = 0
    skipped_empty = 0
    written = 0
    genre_counts: dict[str, int] = {}

    out_fields = [
        "band", "filename", "genre",
        "tempo_bpm", "tempo_confidence",
        "key_name", "mode",
        "energy", "danceability", "valence", "acousticness",
        "lufs_integrated", "dynamic_range_db",
        "spectral_centroid", "spectral_rolloff", "zero_crossing_rate",
    ]

    with open(src, encoding="utf-8-sig") as fin, \
         open(dst, "w", encoding="utf-8", newline="") as fout:

        reader = csv.DictReader(fin)
        writer = csv.DictWriter(fout, fieldnames=out_fields, extrasaction="ignore")
        writer.writeheader()

        for raw in reader:
            status = raw.get("status_analise", "").strip()
            if status == "falha_total":
                skipped_status += 1
                continue

            artista = raw.get("artista", "").strip()
            arquivo = raw.get("arquivo", "").strip()
            if not artista or not arquivo:
                skipped_empty += 1
                continue

            filename = Path(arquivo).name
            genre = ARTIST_GENRE.get(artista, DEFAULT_GENRE)
            key_name, mode = parse_key(raw.get("tom_musical", ""))

            row = {
                "band": artista,
                "filename": filename,
                "genre": genre,
                "tempo_bpm": safe_float(raw.get("bpm", "")),
                "tempo_confidence": safe_float(raw.get("confianca_tom", "")),
                "key_name": key_name,
                "mode": mode,
                "energy": safe_float(raw.get("energia", "")),
                "danceability": safe_float(raw.get("dancabilidade", "")),
                "valence": safe_float(raw.get("sentimento_valence", "")),
                "acousticness": safe_float(raw.get("acousticidade", "")),
                "lufs_integrated": safe_float(raw.get("loudness_lufs", "")),
                "dynamic_range_db": safe_float(raw.get("alcance_dinamico_db", "")),
                "spectral_centroid": safe_float(raw.get("centroide_espectral_hz", "")),
                "spectral_rolloff": safe_float(raw.get("rolloff_espectral_hz", "")),
                "zero_crossing_rate": safe_float(raw.get("zero_crossing_rate", "")),
            }
            writer.writerow(row)
            written += 1
            genre_counts[genre] = genre_counts.get(genre, 0) + 1

    print(f"\n✓ Concluído: {written} faixas escritas")
    print(f"  Pulados (falha_total): {skipped_status}")
    print(f"  Pulados (artista/arquivo vazio): {skipped_empty}")
    print(f"\n  Distribuição por gênero:")
    for g, n in sorted(genre_counts.items(), key=lambda x: -x[1]):
        print(f"    {n:5d}  {g}")
    print(f"\n  Arquivo gerado: {dst}")
    print(f"\n  Próximo passo: faça upload em /admin/reference-tracks")


def main() -> None:
    parser = argparse.ArgumentParser(description="Transforma CSV de análise para o formato de import")
    parser.add_argument("input", help="Caminho do CSV de entrada (diagnostico_sonara_artistas.csv)")
    parser.add_argument("--output", default="/tmp/reference_tracks_import.csv",
                        help="Caminho do CSV de saída (padrão: /tmp/reference_tracks_import.csv)")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Arquivo não encontrado: {args.input}", file=sys.stderr)
        sys.exit(1)

    transform(args.input, args.output)


if __name__ == "__main__":
    main()
