import { describe, it, expect, vi, beforeAll, afterAll } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import ProjectTasksTab from "../ProjectTasksTab";
import type { Task } from "@/hooks/useTasks";

beforeAll(() => {
  vi.useFakeTimers();
  vi.setSystemTime(new Date("2026-01-15T12:00:00Z"));
});
afterAll(() => {
  vi.useRealTimers();
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: "t-1",
    userId: "u-1",
    projectId: "proj-1",
    description: "Sample task",
    dueDate: null,
    completed: false,
    autoGenerated: false,
    source: "manual",
    sourceKey: "",
    createdAt: "2026-01-01T00:00:00Z",
    assignedTo: "",
    blocked: false,
    blockedReason: "",
    severity: "medium",
    taskArea: "geral",
    sourceModule: "",
    ...overrides,
  };
}

// ── Mock useTasks ─────────────────────────────────────────────────────────────

const mockHook = vi.hoisted(() => ({
  activeTasks: [] as Task[],
  completedTasks: [] as Task[],
  addTask: vi.fn(),
  toggleTask: vi.fn(),
  deleteTask: vi.fn(),
}));

vi.mock("@/hooks/useTasks", async (importOriginal) => {
  const real = await importOriginal<typeof import("@/hooks/useTasks")>();
  return {
    ...real,
    useTasks: () => mockHook,
  };
});

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("ProjectTasksTab component", () => {
  it("shows empty state when there are no tasks", () => {
    mockHook.activeTasks = [];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Nenhuma tarefa neste projeto ainda.")).toBeInTheDocument();
  });

  it("renders the add-task input", () => {
    mockHook.activeTasks = [];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByPlaceholderText("Nova tarefa…")).toBeInTheDocument();
  });

  it("shows 'Vencidas' section for overdue tasks", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", dueDate: "2026-01-10", description: "Overdue task" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Vencidas")).toBeInTheDocument();
    expect(screen.getByText("Overdue task")).toBeInTheDocument();
  });

  it("shows 'Hoje' section for tasks due today", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", dueDate: "2026-01-15", description: "Today task" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    // "Hoje" appears both as section header and as due-date badge — both are expected
    expect(screen.getAllByText("Hoje").length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText("Today task")).toBeInTheDocument();
  });

  it("shows 'Esta semana' section for tasks due within 7 days", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", dueDate: "2026-01-20", description: "Week task" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Esta semana")).toBeInTheDocument();
  });

  it("shows 'Bloqueadas' section for blocked tasks", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", blocked: true, description: "Blocked task", blockedReason: "Aguardando aprovação" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Bloqueadas")).toBeInTheDocument();
    expect(screen.getByText("Blocked task")).toBeInTheDocument();
    expect(screen.getByText("Aguardando aprovação")).toBeInTheDocument();
  });

  it("shows 'Futuras / Sem prazo' section for tasks with no due date", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", dueDate: null, description: "No due date task" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Futuras / Sem prazo")).toBeInTheDocument();
  });

  it("only shows tasks belonging to the given projectId", () => {
    mockHook.activeTasks = [
      makeTask({ id: "t1", projectId: "proj-1", description: "My project task" }),
      makeTask({ id: "t2", projectId: "proj-2", description: "Other project task" }),
    ];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("My project task")).toBeInTheDocument();
    expect(screen.queryByText("Other project task")).not.toBeInTheDocument();
  });

  it("displays the active task count badge", () => {
    mockHook.activeTasks = [
      makeTask({ id: "t1", description: "Task A" }),
      makeTask({ id: "t2", description: "Task B" }),
    ];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Task A")).toBeInTheDocument();
    expect(screen.getByText("Task B")).toBeInTheDocument();
  });

  it("shows completed section trigger when completed tasks exist", () => {
    mockHook.activeTasks = [];
    mockHook.completedTasks = [makeTask({ id: "c1", completed: true, description: "Done task" })];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText(/Concluídas \(1\)/)).toBeInTheDocument();
  });

  it("shows overflow indicator when completed tasks exceed limit", () => {
    mockHook.activeTasks = [];
    mockHook.completedTasks = Array.from({ length: 13 }, (_, i) =>
      makeTask({ id: `c${i}`, completed: true, description: `Done ${i + 1}` })
    );
    render(<ProjectTasksTab projectId="proj-1" />);
    // Open the collapsible to reveal the overflow indicator (overflow = 13 - 10 = 3)
    fireEvent.click(screen.getByText(/Concluídas \(13\)/));
    expect(screen.getByText(/\+ 3/)).toBeInTheDocument();
  });

  it("shows blocked-task fallback label when blockedReason is empty", () => {
    mockHook.activeTasks = [makeTask({ id: "t1", blocked: true, blockedReason: "", description: "Blocked no reason" })];
    mockHook.completedTasks = [];
    render(<ProjectTasksTab projectId="proj-1" />);
    expect(screen.getByText("Bloqueada")).toBeInTheDocument();
  });
});
