
-- Add new columns to tasks table
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS assigned_to TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS blocked BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS blocked_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS severity TEXT NOT NULL DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS task_area TEXT NOT NULL DEFAULT 'geral',
  ADD COLUMN IF NOT EXISTS source_module TEXT NOT NULL DEFAULT '';
