
-- Add freelancer/plan fields to profiles table
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS plan TEXT NOT NULL DEFAULT 'pro',
  ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'signup',
  ADD COLUMN IF NOT EXISTS whatsapp TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS specialties TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS accept_invites BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS projects_completed INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS public_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS allow_global_listing BOOLEAN NOT NULL DEFAULT false;
