
ALTER TABLE public.project_messages
  ADD COLUMN IF NOT EXISTS is_pending BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_resolved BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS linked_task_id UUID,
  ADD COLUMN IF NOT EXISTS attachment_path TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS attachment_name TEXT NOT NULL DEFAULT '';
