// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qozsvdnvoqxwvhtzksde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvenN2ZG52b3F4d3ZodHprc2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDA3ODMsImV4cCI6MjA3NDMxNjc4M30.7s5GmYT0DtUeUMZOmjRDhwKlLYDkONUVRb1C-FnU3J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});